
-- --------------------------------------------------------

--
-- Table structure for table `deckindex`
--

CREATE TABLE `deckindex` (
  `ID` int(10) UNSIGNED NOT NULL,
  `DeckKeyword` varchar(45) NOT NULL,
  `DeckDescription` varchar(50) NOT NULL,
  `DeckMetaKeywords` varchar(500) NOT NULL,
  `DeckAuthors` varchar(100) NOT NULL,
  `DeckLore` varchar(3000) NOT NULL,
  `DeckNameSeo` varchar(100) NOT NULL,
  `DeckAbstract` varchar(200) NOT NULL,
  `DeckYear` int(11) NOT NULL DEFAULT 2004,
  `SpecialDeck` int(11) NOT NULL DEFAULT 0,
  `IsActive` varchar(1) NOT NULL DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci ROW_FORMAT=COMPACT;

--
-- Dumping data for table `deckindex`
--

INSERT INTO `deckindex` (`ID`, `DeckKeyword`, `DeckDescription`, `DeckMetaKeywords`, `DeckAuthors`, `DeckLore`, `DeckNameSeo`, `DeckAbstract`, `DeckYear`, `SpecialDeck`, `IsActive`) VALUES
(1, 'Anime', 'Anime Deck', 'anime deck, final fantasy anime, anime cards, anime videos', 'Darkjaxychan', '', 'Anime-Deck', '', 2004, 0, '1'),
(2, 'Anime2', 'Anime 2 Deck', 'anime deck, final fantasy anime, anime cards, anime videos', 'J102Y', '', 'Anime-2-Deck', '', 2004, 0, '1'),
(3, 'CC', 'Chrono Cross Deck', 'chrono cross, playstation games, psx games, cc, chrono cross cards, chrono cross rom', 'Jimmy3000', '', 'Chrono-Cross-Deck', '', 2004, 0, '1'),
(4, 'Crusade', 'Chrono Crusade Deck', 'chrono crusade, crusade, crusade video, anime videos, anime series', 'Sundragon', '', 'Chrono-Crusade-Deck', '', 2004, 0, '1'),
(5, 'DQ8', 'Dragon Quest 8 Deck', 'dragon quest, dragon quest 8, dragon quest viii, playstation 2, psx2', 'Glacial89|Y2Trips', 'Dragon Quest 8 is one of many in the Dragon Quest series.  Originally known as Dragon Warrior in the US, DQ8 was released in November of 2005 for PlayStation 2. This classic style turn-based RPG was a huge success compared to the series’ previous releases. <BR><BR>While most games in the series have well over 300 monsters, this deck includes only about 100 monsters but gives a good representation of the hero’s most common and well known adversaries. All main plot characters are also included as high level cards.  The SE cards include 3 dragons from the game’s main “side quest”, an alchemy pot which creates the strongest weapons/armor/items in the game, and the landscape of the Trodian Empire.<BR><BR>A nameless hero is in pursuit of an evil jester Dhoulmagus who stole a magical scepter from the Trodain castle.  Dhoulmagus uses the scepter to place a curse on King Trode and Princess Medea to give them ghastly appearances as well as cover all of Trodain castle and its inhabitants in thorns.  As the plot continues, Hero is joined by three companions: Yangus a bumbling fool, Jessica a beautiful mage, and Angelo a charismatic knight.  Each has their own reason for seeking vengeance against Dhoulmagus and they begin a long journey.  It is later discovered that the source of the scepter’s evil power is Rhapthorne, The Lord of Darkness.  The party continues to pursue different possessors of the scepter and in the end, confronts and defeats Rhapthorne.  The curse is lifted and order is restored to the world and the Trodain Empire.', 'Dragon-Quest-8-Deck', '', 2004, 0, '1'),
(6, 'FF6', 'Final Fantasy 6 Deck', 'final fantasy 3, final fantasy 6, final fantasy iii, final fantasy vi, final fantasy cards, final fantasy triple triad', 'SgShadow', '', 'Final-Fantasy-6-Deck', '', 2004, 0, '1'),
(7, 'FF7', 'Final Fantasy 7 Deck', 'final fantasy 7, final fantasy vii, final fantasy cards, final fantasy triple triad', 'J102Y', '', 'Final-Fantasy-7-Deck', '', 2004, 0, '1'),
(8, 'FF9', 'Final Fantasy 9 Deck', 'final fantasy 9, final fantasy ix, final fantasy cards, final fantasy triple triad', 'Jimmy3000', '', 'Final-Fantasy-9-Deck', '', 2004, 0, '1'),
(9, 'FFAC', '(X) Final Fantasy: Advent Children Event Deck', 'final fantasy 7, final fantasy 7 ac, ffac, advent children, final fantasy vii, final fantasy cards, final fantasy triple triad', 'Kadajiroth', '', 'Final-Fantasy-Advent-Children-Event-Deck', '', 2004, 1, '0'),
(10, 'FFT', 'Final Fantasy Tactics Deck', 'final fantasy tactics, fft, final fantasy cards, final fantasy triple triad', 'Jinx', '', 'Final-Fantasy-Tactics-Deck', '', 2004, 0, '1'),
(11, 'FFTA', 'Final Fantasy Tactics Advanced Deck', 'final fantasy tactics advanced, tactics advanced, psp, ffta, final fantasy cards, final fantasy triple triad', 'Psychemaster', ' ', 'Final-Fantasy-Tactics-Advanced-Deck', '', 2004, 0, '1'),
(12, 'FFX', 'Final Fantasy X Deck', 'final fantasy x, final fantasy 10, final fantasy cards, final fantasy triple triad', 'Kadajiroth', ' ', 'Final-Fantasy-X-Deck', '', 2004, 0, '1'),
(13, 'FFXII', 'Final Fantasy XII Deck', 'final fantasy 12, final fantasy xii, final fantasy cards, final fantasy triple triad', 'J102Y', ' ', 'Final-Fantasy-XII-Deck', '', 2004, 0, '1'),
(14, 'FireEmblem', 'Fire Emblem Deck', 'fire emblem, final fantasy cards, final fantasy triple triad', 'J102Y', ' ', 'Fire-Emblem-Deck', '', 2004, 0, '1'),
(15, 'Halloween', '(X) Halloween Holiday Event Deck', 'halloween, special cards, event cards, final fantasy cards, final fantasy triple triad', 'J102Y', ' ', 'Halloween-Holiday-Event-Deck', '', 2004, 1, '0'),
(16, 'Johto', 'Johto Pokemon Deck', 'pokemon, all pokemon, johto, johto cards, johto expansion, johto league, pokemon card game, pokemon trading cards', 'Legendfox', ' ', 'Johto-Pokemon-Deck', '', 2004, 0, '1'),
(17, 'Kanto', 'Kanto Pokemon Deck', 'pokemon, all pokemon, pokemon pokemon, kanto, kanto cards, kanto expansion, pokemon card game, pokemon trading cards', 'Legendfox', ' ', 'Kanto-Pokemon-Deck', '', 2004, 0, '1'),
(18, 'KingdomHearts', 'Kingdom Hearts Deck', 'kingdom hearts, kingdom hearts game, playstation, playstation 2', 'Solidsnake|J102Y', ' ', 'Kingdom-Hearts-Deck', '', 2004, 0, '1'),
(19, 'Legends', 'Legends Deck', 'halo, halo3, conker, gears of war, gears of war 3, gears of war 4, xbox, xbox360', 'J102Y', 'Whilst many of gaming\'s noteable characters found their place on Triple Triad Extreme, there existed some who sought after a place too. Knowing that there was little option of appearing alongside the likes of these fabled Sword-wielders, many gun-toting hard-hitting \'Legends\' banded together to seal themselves\r\na place within Triple Triad Extreme. Master Chief, one of the most recognized characters in the last decade joins  forces with Marcus Fenix and his band of COG soldiers, and his enemies, while the ever-lovely Dead or Alive girls make an appearance alongside longtime babes, Joanna Dark and Lara Croft. Not forgetting Crowbar veteran,\r\nGordon Freeman, who is portrayed as a \'Video Game Nerd\' by the Splinter Cell Team. Crash Bandicoot along with his allies and enemies, join the band of Legends to prove you don\'t need a gun to be awesome.<br />\r\n<br />\r\n(Heck, Wumpa Fruit hurling Bazooka\'s are way better in his opinion) <br />\r\n<br />\r\nFriend and foe alike from Left 4 Dead continue their struggle for survival as they get their claws into the deck along with the Dead Rising crew, led by Frank West, He\'s covered wars, you know. <br />\r\n<br />\r\nThese Legends prove that you don\'t have to have a sword to be accepted, But, it sure does help.', 'Legends-Deck', '', 2004, 0, '1'),
(20, 'Nintendo', 'Nintendo Deck', 'nintendo, yoshi, mario, nintendo cards, nintendo collectibles', 'J102Y', ' ', 'Nintendo-Deck', '', 2004, 0, '1'),
(21, 'NXC', 'Namco vs. Capcom Deck', 'namco heroes, namco villians, capcom heroes, capcom villians, NXC', 'Halfas', ' ', 'Namco-vs-Capcom-Deck', '', 2004, 0, '1'),
(22, 'Sega', 'Sega Deck', 'sega heroes, sonic the hedgehog, sonic', 'J102Y', ' ', 'Sega-Deck', '', 2004, 0, '1'),
(23, 'SMT', 'Shin Megami Tensei Deck', 'shin megami tensei, shin, megami, tensei, anime, anime card game, anime trading cards', 'Legendfox', ' ', 'Shin-Megami-Tensei-Deck', '', 2004, 0, '1'),
(24, 'Standard', 'Final Fantasy 8 Deck', 'final fantasy 8, final fantasy viii, final fantasy cards, final fantasy triple triad', 'J102Y', ' ', 'Final-Fantasy-8-Deck', '', 2004, 0, '1'),
(25, 'Suikoden2', 'Suikoden 2 Deck', 'suikoden 2, suikoden ii, chinchirorin', 'Darkjaxychan', ' ', 'Suikoden-2-Deck', '', 2004, 0, '1'),
(26, 'Suikoden3', 'Suikoden 3 Deck', 'suikoden 3, suikoden iii, chinchirorin', 'Power', ' ', 'Suikoden-3-Deck', '', 2004, 0, '1'),
(27, 'XenoTrigger', 'Xeno Trigger Deck', 'xenotrigger, xenogears, chrono trigger, playstation games, playstation roms', 'Jimmy3000', ' ', 'Xeno-Trigger-Deck', '', 2004, 0, '1'),
(28, 'Valentines', '(X) Valentines Holiday Event Deck', 'valentines day, valentines cards, valentines candy, valentines holiday', 'ShadowM|Solidsnake|Monmas', '', 'Valentines-Holiday-Event-Deck', '', 2004, 1, '0'),
(29, 'Suikoden1', 'Suikoden 1 Deck', 'suikoden 1, suikoden i, chinchirorin', 'Jinvicious|Power', '', 'Suikoden-1-Deck', '', 2004, 0, '1'),
(30, 'MarvelDC', 'Marvel vs DC Comics', 'marvel, dc comics, superman, batgirl, spiderman', 'Kadajiroth|Aaxel', 'This deck contains the most known characters that originated from the comic form of both the Marvel and DC Comics comic book franchises. Included are the most popular of comics and characters, such as Spiderman, Iron Man, X-Men , Batman, Superman, Watchmen, Wonder Woman, and many others. Triple Triad Extreme brings you the Marvel vs DC Universe deck.<br />\r\n<br />\r\n<a href=\"http://www.marvel.com/\" target=\"_new\">Marvel</a> was created in 1939 as “Timely Publications”, and by the 1950s was known as Atlas Comics. Marvel has grown to become the largest American comic book publisher, beating long-time competitor company “DC Comics”. Most of Marvel’s fictional characters are situated in a single reality or universe, which is known as the Marvel Universe. Marvel is most famous for comic books as Spider-Man, X-Men, the Fantastic Four and Iron Man.<br />\r\n<br />\r\n<a href=\"http://www.dccomics.com/\" target=\"_new\">DC Comics</a>, also one of the world’s largest publishers of comic books, has been a subsidary of Warner Bros. since 1969. The publisher’s initials, “DC”, originated from the company’s popular comic book series “Detective Comics”. Unlike Marvel (where the majority of characters exist in the single universe), DC Comics’ fictional characters are known to exist in a Multiverse, which contains multiple separate universes, on some occasions known to combine. DC Comics is most famous for the characters Batman, Superman and Wonder Woman. Another essential comic book (or graphic novel) included in this deck is one of the highest-rated graphic novels of all time “Watchmen”, and the graphic novel by the same creator “V for Vendetta”.<br />\r\n<br />\r\nBe on the lookout for the classic and iconic Special Edition and Event Cards, such as “End of Krypton”, “The Dark Knight” and “Civil War”.<br />\r\n<br />\r\nThis deck was created to include the most iconic comic book characters out of the respective franchises for the comic book and superhero fan in-mind.\r\n', 'Marvel-vs-DC-Comics', '', 2004, 0, '1'),
(31, 'GodofWar', 'God of War', 'god of war, xbox360', 'Glacial89', 'God of War is an action-adventure game based on Greek mythology. This deck includes the characters from God of War and God of War 2. Only few from God of War Chain of Olympus \r\n\r\nKratos is a Spartan who offered his service to the God of War (Ares) to defeat the Barbarians king and his strong army. In that moment Kratos became Ares’ slave and begins to kills people. He defeats armies in the name of the God of War. That is until one day when Ares makes him kill his wife and daughter.  From that moment on, Kratos swears revenge against Ares. With the help of the Gods of the Olympus, Kratos finds Pandora’s Box which gives him the power of the Gods. With that power, Kratos defeats Ares and become the new God of War.\r\n\r\nIn God of War 2, Kratos loses his power of the gods and is killed by Zeus because he won’t promise to serve him forever. The Titans help Kratos escape from underworld and take revenge against Zeus. After Kratos defeats the Sisters of Fate, he travels through time to the moment when Zeus is killing him and they begin to fight.  As Kratos is about to defeat Zeus, Athena saves the King of the Gods by sacrificing herself to protect Olympus. In that moment, Kratos and the Titans go to Mount Olympus to take their revenge against Zeus and the Gods whose still serve him...', 'God-of-War', '', 2004, 0, '0'),
(32, 'Lenneth', 'Valkyrie Profile: Lenneth', 'valkyrie profile lenneth, lenneth, valkyrie, psp, playstation', 'Power', 'Valkyrie Profile is a RPG published by Tri-Ave and developed in the year 2000 by Enix.\r\n\r\nIn the Year 2006 a remake for the PSP was realesed. The Story is based on Nordic Mythologies.\r\nYou are playing Lenneth 1 of 3 Valkries which are under the Lead of Lord Odin the God of Vallhalla.\r\nVallhalla is in a War against their enemies and the underground of Nifelheim. Lord Odin sends Lenneth to\r\nMidgard the place were the human live to collect worthy Einherjahrs (Fighters) which will fight at Vallhalla \r\nfor the Gods. At the beginning, it seems really clear who is evil and who is good, but the longer the story \r\nis proceeding it becomes increasingly difficult to see who is right and who is wrong. The story holds many \r\nsurprises for the player and guarantees a lot of fun in gameplay and storyline.', 'Valkyrie-Profile-Lenneth', '', 2004, 0, '0'),
(33, 'Summer', '(X) Extreme Summer', 'extreme summer, kasumi bikini, manga, aeris, sora, summer event', 'Glacial89', '', 'Extreme-Summer', '', 2004, 1, '0'),
(34, 'Christmas', '(X) Christmas Event Deck', 'christmas event deck, christmas cards, special edition', 'Darkjaxychan', '', 'Christmas-Event-Deck', '', 2004, 1, '0'),
(35, 'DuelMonsters', 'Duel Monsters Deck', 'yugioh, yugioh 5d, duel monsters, dark magician girl', 'Glacial89', 'The Yu-Gi-Oh! Trading Card is a Japanese collectible card game developed and published by Konami. It is based on the fictional game of Duel Monsters created by comic artist Kazuki Takahashi, which is the main plot device during the majority of his popular comic Yu-Gi-Oh! and the Nihon Ad Systems animated series Yu-Gi-Oh! Duel Monsters, Yu-Gi-Oh! Duel Monsters GX and Yu-Gi-Oh! 5Ds. In the fictional settings of the manga, anime, and films, the game is referred to as Duel Monsters. The trading card game is the realization of a fictional game which was invented by the author Kazuki Takahashi. Konami has produced most of the cards named by Takahashi with the powers he gives them. This deck is composed of 125 monsters cards that belong to the main characters of the entire Yu-Gi-Oh series.', 'Duel-Monsters-Deck', '', 2004, 0, '0'),
(36, 'FF3', 'Final Fantasy 3 Deck', 'final fantasy 3, final fantasy 3 ds, final fantasy nes, final fantasy iii, final fantasy game', 'Glacial89', 'Final Fantasy III is the third installment in the Final Fantasy series, developed by Square Co., Ltd., released on the Nintendo Family Computer (Famicom) and remade for the Nintendo DS. In the original NES version of the game, the player controlled four generic Light Warriors, four children without distinct identities, who literally fall into their adventure and upon finding the Wind Crystal were granted its power in order to save the world. The DS remake gives the four protagonists different personalities and names. The main character is Luneth, who, after being tasked with saving the other worlds Crystals, heads forth with his best friend Arc in pursuit of his quest. Shortly after setting out, they meet the blacksmiths daughter, Refia, and the Knight of Sasune, Ingus. Together they start the journey to save the world…', 'Final-Fantasy-3-Deck', '', 2004, 0, '0'),
(37, 'Halloween2009', '(X) Halloween 2009 Deck', 'trading cards, pokemon trading cards, tcg cards, cards deck, silent hill, fatal frame, resident evil, fear, parasite eve, vampire night, nemesis', 'Glacial89', 'For this deck the most known and popular horror games have been choosen. From Fatal Frame to the kings of Horror games as Resident Evil and Silent Hill,  From Parasite Eve to Fear, and then Fahrenheit and Vampire Night. Bosses like Lord Saddler and Nemesis respectively from resident evil 3 and 4 couldve not being missing. Project Zeros ghosts like Sae and Reika as well.', 'Halloween-2009-Deck', '', 2009, 1, '0'),
(38, 'MegamanZero', 'Megaman Zero Deck', 'megaman x, megaman, mega man zero, megaman zero, megaman zero 2, megaman zero 3, megaman zero 4, megaman x zero, megaman games online', 'Kuisami', 'Megaman Zero is the next installment of the Megaman series taking place after the events of Megaman X in the year 23XX. In this series, the player assumes the control of Zero, one of the main protagonists from the X series. The series begins as Zero is awakened from his self induced sleep and is unsealed by the leader of the Neo Arcadia Resistance, Ciel. With the aid of the Resistance, Zeroventures to take down the oppression and dictatorship that is Neo Arcadia and its leader, Copy X, later Dr. Weil. The deck includes all major characters, support characters, bosses, most of the sub-bosses, and the Pantheon legion.', 'Megaman-Zero-Deck', '', 2004, 0, '0'),
(39, 'Hoenn', 'Hoenn Deck', 'hoenn, pokemon, pokemon trading cards, pokemon cards, all pokemon', 'Monmas', 'A new adventure starts out in Oldale Town \"where things start off scarce\", you set out to explore the world with your very own new Pokemon which you receive from Professor Birch, the Hoenn Regions Professor.\r\nHere in Hoenn you have a choice out of the Firey Starter Pokemon Torchic, the Lively Treecko or the Popular Mudkip. Once you pick, you are now set out and ready for your adventure to meet the 8 new Gym Leaders and discover the 135 new Pokemon that the Hoenn Region offers.\r\nNew Pokemon aren’t the only thing new in this region either, there are now Contests which is yet another way to compete against friends, you can mix and grow berries and challenge the all new Team Magma and Team Aqua.\r\nThe Hoenn deck features 139 new cards to play with including 4 Special Edition cards which feature the new revolutionary items to the Hoenn Region and the trouble making Team Aqua and Team Magma. Will you prove that you are a true Pokemon Master and complete the whole deck?', 'Hoenn-Deck', '', 2004, 0, '0'),
(40, 'WorldofWarcraft', 'World of Warcraft Deck', 'world of warcraft, wow, wow trading cards, world of warcraft trading cards, triple triad wow cards', 'Darkjaxychan|Aska', '', 'World-of-Warcraft-Deck', '', 2004, 0, '0'),
(41, 'Christmas2009', '(X) Christmas 2009 Deck', 'christmas deck, christmas trading cards, christmas 2009, holiday trading cards', 'Monmas', '', 'Christmas-2009-Deck', '', 2009, 1, '0'),
(42, 'WorldofMana', 'World of Mana Genesis', 'secret of mana, world of mana, world of mana genesis', 'ShadowM', 'Experience the start of Square\'s Mana craze with this 124-card set including 4 Special Edition and Event cards, along with all new number combinations.\r\nCollect all your favorite enemies from Rabite to the Mana Beast aswell featuring your favorite characters from the classic games: Secret of Mana, Seiken Densetsu 3 and the Secret of Evermore.\r\n\r\nEach generation, a new generation of heroes are born to protect the Mana World from the evil villians which attempt harbor the source of Mana to destroy the world and become evil Gods.\r\nMeet new people who will support you all the way while you are on your journey.\r\n\r\nGenesis is the birth of a new series with more to be expected.', 'World-of-Mana-Genesis', '', 2004, 0, '0'),
(43, 'Valentines2010', '(X) Valentines 2010 Deck', 'valentines cards, valentines trading cards, valentines 2010 event cards, valentines game, valentines day', 'Monmas', '', 'Valentines-2010-Deck', '', 2010, 1, '0'),
(44, 'Summer2010', '(X) Summer 2010 Deck', 'summer 2010, trading card game, event cards', 'Monmas|Mitsu', '', 'Summer-2010-Deck', '', 2010, 1, '0'),
(45, 'DigimonDestiny', 'Digimon Destiny Deck', 'digimon destiny, catch them all, pokemon, pokemon trading cards', 'Shuyin987', 'Find yourself called to a remote island inside a Digital World, filled with over sized electronical parts and strange creatures. This new deck features 114 cards from the first Digimon era, which will introduce the Digidestined Digimon and the evil organizations such as the Dark Masters. Get ready to collect an array of new elemental cards and number combinations to satisfy even the greatest Digimon fans.', 'Digimon-Destiny-Deck', '', 2004, 0, '0'),
(46, 'TTE10th', '(X) TTE 10th Anniversary Deck', 'tte 10th anniversary, tto, questria, triple triad, triple triad extreme', 'Monmas|Mitsu|Atomicstorm', 'Obtain all the popular cards from the last 10 years in this event deck.  It will be expanded each year.', 'TTE-10th-Anniversary-Deck', '', 2010, 1, '0'),
(47, 'CLAMP', 'CLAMP Deck', 'CLAMP, manga, anime, shoujo, magic knight, card captor sakura', 'Sunstar259', 'CLAMP is a group of manga writers and artists that are known to have their manga adapted into anime.  Considered anime of the shoujo (target audience: girls) genre, the guys generally look better than average and the ladies are considered cute with the plot elements generally emphasizing relationships.  As a tribute to their older manga into anime adaptations, the deck features characters and other important things (clow cards in the case of Card Captor Sakura) from three of their pieces of work: Magic Knight Rayearth (1994), Card Captor Sakura (1998), and Angelic Layer (2001).', 'CLAMP-Deck', '', 2010, 0, '0'),
(48, 'OdinSphere', 'Odin Sphere Deck', 'odin sphere, triple triad, trading card game', 'Kimhy|Darkjaxychan', 'The story of Odin Sphere unfolds via an interesting convention: a young girl\r\nin an attic picks up one of five books, each featuring a separate hero,\r\nwhose various stories intertwine to give the overall picture of the now war-torn\r\nlands of Erion. Players will unlock the secrets behind the game by exploring\r\nthe adventures of each character, discovering how their actions play into\r\nthe overall tale. While I won\'t give away plot specifics, much of the\r\nstory revolves around a powerful magical artifact left behind from a\r\ndestroyed kingdom known as the Crystallization Cauldron. Some of the\r\nkingdoms in the land, including the Fairy kingdom of Ringford and the\r\nland of Ragnanival, lead by the Demon Lord Odin, clash over control of the\r\nobject. Unbeknownst to the leaders, possession of the object could quite\r\npossibly lead to the destruction of the world.', 'Odin-Sphere-Deck', '', 2010, 0, '0'),
(49, 'FF2', 'Final Fantasy 2 Deck', 'final fantasy, final fantasy 2, final fantasy ii, super nintendo', 'Derfas13', 'Final Fantasy II is the second installment in the Final Fantasy Series. It is notable for being\r\none of the first story-intensive RPGs released for a console system, and for being the first game in\r\nthe series to feature many elements that would later become staples of the Final Fantasy franchise,\r\nincluding chocobos and a character by the name of Cid.<BR>\r\n<BR>\r\nThe story concerns the adventures of four youngsters from the kingdom of Fynn named Firion,\r\nMaria, Guy and Leon. Their parents are killed during an invasion by the army of The Emperor of Palamecia,\r\nwho has summoned forth monsters from Hell in his quest to dominate the world. Fleeing the Emperor\'s\r\nmonsters, the four are attacked and left for dead. Firion, Maria, and Guy are rescued by Princess Hilda\r\nof Fynn, who has established a rebel base in the nearby town of Altair. Eager to prove their value to\r\nthe resistance movement, the three remaining youths undertake a variety of missions against Palamecia\r\nand join forces with a variety of allies not only to defeat the Emperor, but to locate Maria\'s missing\r\nbrother Leon as well.', 'Final-Fantasy-2-Deck', '', 2011, 0, '0'),
(50, 'FF4', 'Final Fantasy 4 Deck', 'final fantasy, final fantasy 4, final fantasy iv, super nintendo', 'Zeromus', '', 'Final-Fantasy-4-Deck', '', 2011, 0, '0'),
(51, 'Christmas2010', '(X) Christmas 2010 Deck', 'christmas 2010, event deck, special triple triad cards', 'Monmas', '', 'Christmas-2010-Deck', '', 2010, 1, '0'),
(52, 'Charity', '(X) Charity Deck', 'charity trading cards, triple triad, triple triad donations', 'Zeromus', '', 'Charity-Deck', '', 2011, 1, '0'),
(53, 'Summer2011', '(X) Summer 2011 Deck', 'summer 2011, event deck, special triple triad cards, triple triad', 'Ekibiogami', '', 'Summer-2011-Deck', '', 2011, 1, '0'),
(54, 'Halloween2011', '(X) Halloween 2011 Deck', 'halloween deck 2011, anime event deck, triple triad cards', 'Ekibiogami', '', 'Halloween-2011-Deck', '', 2011, 1, '0'),
(55, 'FF5', 'Final Fantasy 5 Deck', 'final fantasy 5, final fantasy v, triple triad', 'Darkjaxychan|Aska', '', 'Final-Fantasy-5-Deck', '', 2012, 0, '0'),
(56, 'DragonWarrior', 'Dragon Warrior Deck', 'dragon warrior, dragon question, square enix', 'forumadmin', '', 'Dragon-Warrior-Deck', '', 2021, 0, '1');
