
-- --------------------------------------------------------

--
-- Table structure for table `configuration`
--

CREATE TABLE `configuration` (
  `ConfigID` int(10) UNSIGNED NOT NULL,
  `ConfigKeyword` varchar(45) NOT NULL,
  `ConfigValue` varchar(8000) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci ROW_FORMAT=COMPACT;

--
-- Dumping data for table `configuration`
--

INSERT INTO `configuration` (`ConfigID`, `ConfigKeyword`, `ConfigValue`) VALUES
(1, 'AP1', '100'),
(2, 'AP2', '10'),
(3, 'GP1', '1'),
(4, 'GP2', '1'),
(5, 'TTJackpot', '231709'),
(6, 'THJackpot', '0'),
(7, 'MailTax', '5'),
(8, 'GoldTax', '5'),
(9, 'CardTax', '5'),
(10, 'CardLoreApprovalGPAward', '100'),
(11, 'CardLoreApprovalEXPAward', '0'),
(12, 'ShopLimitPenalty', '0.10'),
(13, 'LootCardPaypalBlob', '<form target=\"paypal\" action=\"https://www.paypal.com/cgi-bin/webscr\" method=\"post\">\r\n<input type=\"image\" src=\"https://www.paypal.com/en_US/i/btn/x-click-but22.gif\" border=\"0\" name=\"submit\" alt=\"Make payments with PayPal - it\'s fast, free and secure!\">\r\n<input type=\"hidden\" name=\"add\" value=\"1\">\r\n<input type=\"hidden\" name=\"cmd\" value=\"_cart\">\r\n<input type=\"hidden\" name=\"business\" value=\"gamewar@yahoo.com\">\r\n<input type=\"hidden\" name=\"on0\" value=\"Player Name\">\r\n<input type=\"hidden\" name=\"os0\" value=\"%%Player%%\">\r\n<input type=\"hidden\" name=\"item_name\" value=\"Loot Card: %%Card%%\">\r\n<input type=\"hidden\" name=\"item_number\" value=\"%%Card%%\">\r\n<input type=\"hidden\" name=\"amount\" value=\"%%Price%%\">\r\n<input type=\"hidden\" name=\"page_style\" value=\"PayPal\">\r\n<input type=\"hidden\" name=\"no_shipping\" value=\"1\">\r\n<input type=\"hidden\" name=\"no_note\" value=\"1\">\r\n<input type=\"hidden\" name=\"currency_code\" value=\"USD\">\r\n<input type=\"hidden\" name=\"lc\" value=\"US\">\r\n</form>'),
(14, 'RankMod', '10'),
(15, 'GoldWinRate', '45'),
(16, 'GoldLoseRate', '20'),
(17, 'GoldDrawRate', '25'),
(18, 'TTJackpotOccurance', '1950'),
(19, 'MajorVersion', '3'),
(20, 'MinorVersion', '5'),
(21, 'RevisionVersion', '1'),
(22, 'ServerName', 'Main Server'),
(23, 'ServerPort', '4000'),
(25, 'GameID', '2817066'),
(26, 'TurboMinimum', '60'),
(27, 'MOTD', 'Welcome to Triple Triad Extreme! '),
(28, 'DrawEXPModifier', '8'),
(29, 'LossEXPModifier', '5'),
(30, 'SphereWinEXPModifier', '0'),
(31, 'SphereLossEXPModifier', '0'),
(32, 'MemoryWinEXPModifier', '20'),
(33, 'MemoryLossEXPModifier', '10'),
(34, 'TTExperienceEXPModifier', '10'),
(35, 'MaxTables', '51'),
(36, 'BaseVaultSize', '50'),
(37, 'RushBase', '4'),
(38, 'RushDecay', '0.20'),
(39, 'RushBreak', '100'),
(40, 'NewPlayerInfractionBase', '5'),
(41, 'InfractionBase', '10'),
(42, 'InfractionCost', '500'),
(43, 'RushAPThreshold', '0'),
(44, 'RushGoldThreshold', '430'),
(45, 'RushLootCardThreshold', '490'),
(46, 'RushAPMax', '1000'),
(47, 'RushGoldMax', '250'),
(48, 'AuctionListingFee', '10'),
(49, 'BuyNowListingFee', '20'),
(50, 'FinalListingFee', '3'),
(51, 'TreasureHunterIsActive', '0'),
(52, 'RushOnlineDecay', '0.00'),
(53, 'ShoppingCartPaypalBlob', '<form target=\"paypal\" action=\"https://www.paypal.com/cgi-bin/webscr\" method=\"post\">\r\n<input type=\"image\" src=\"https://www.paypal.com/en_US/i/btn/x-click-but22.gif\" border=\"0\" name=\"submit\" alt=\"Make payments with PayPal - it\'s fast, free and secure!\">\r\n<input type=\"hidden\" name=\"add\" value=\"1\">\r\n<input type=\"hidden\" name=\"cmd\" value=\"_cart\">\r\n<input type=\"hidden\" name=\"business\" value=\"gamewar@yahoo.com\">\r\n<input type=\"hidden\" name=\"on0\" value=\"Player Name\">\r\n<input type=\"hidden\" name=\"os0\" value=\"%%Player%%\">\r\n<input type=\"hidden\" name=\"item_name\" value=\"%%Itemname%%\">\r\n<input type=\"hidden\" name=\"item_number\" value=\"%%ProductKeyword%%\">\r\n<input type=\"hidden\" name=\"amount\" value=\"%%Price%%\">\r\n<input type=\"hidden\" name=\"page_style\" value=\"PayPal\">\r\n<input type=\"hidden\" name=\"no_shipping\" value=\"1\">\r\n<input type=\"hidden\" name=\"no_note\" value=\"1\">\r\n<input type=\"hidden\" name=\"currency_code\" value=\"USD\">\r\n<input type=\"hidden\" name=\"lc\" value=\"US\">\r\n</form>'),
(54, 'SubscriptionPaypalBlob', '<form action=\"https://www.paypal.com/cgi-bin/webscr\" method=\"post\">\r\n<input type=\"hidden\" name=\"cmd\" value=\"_xclick-subscriptions\">\r\n<input type=\"hidden\" name=\"business\" value=\"gamewar@yahoo.com\">\r\n<input type=\"hidden\" name=\"item_name\" value=\"%%Itemname%%\">\r\n<input type=\"hidden\" name=\"no_shipping\" value=\"1\">\r\n<input type=\"hidden\" name=\"return\"\r\nvalue=\"http://www.tripletriadextreme.com/\">\r\n<input type=\"hidden\" name=\"cancel_return\"\r\nvalue=\"http://www.tripletriadextreme.com/\">\r\n<input type=\"hidden\" name=\"on0\" value=\"Player Name\">\r\n<input type=\"hidden\" name=\"os0\" value=\"%%Player%%\">\r\n<input type=\"hidden\" name=\"no_note\" value=\"1\">\r\n<input type=\"hidden\" name=\"currency_code\" value=\"USD\">\r\n<input type=\"hidden\" name=\"lc\" value=\"US\">\r\n<input type=\"hidden\" name=\"bn\" value=\"PP-SubscriptionsBF\">\r\n<input type=\"hidden\" name=\"a3\" value=\"%%Price%%\">\r\n<input type=\"hidden\" name=\"p3\" value=\"1\">\r\n<input type=\"hidden\" name=\"t3\" value=\"M\">\r\n<input type=\"hidden\" name=\"src\" value=\"1\">\r\n<input type=\"hidden\" name=\"sra\" value=\"1\">\r\n<input type=\"hidden\" name=\"no_note\" value=\"1\">\r\n<input type=\"hidden\" name=\"custom\" value=\"customcode\">\r\n<input type=\"image\"\r\n     src=\"http://images.paypal.com/images/x-click-but01.gif\"\r\nborder=\"0\" name=\"submit\"\r\nalt=\"Make payments with PayPal - it’s fast, free and secure!\"> \r\n</form>'),
(55, 'GuildCardCapByMember', '100'),
(56, 'CashReferal', '1.50'),
(57, 'CartReferalPercentage', '0.10'),
(58, 'TTJackpotEnabled', '1'),
(59, 'PingTimeout', '11'),
(60, 'EnableAP', '1'),
(61, 'EnableAvatarShop', '1'),
(62, 'AllowGames', '1'),
(63, 'EvasionPenalty', '1'),
(64, 'TableWagerMultiplier', '0.95'),
(65, 'CardWarsWinEXPModifier', '25'),
(66, 'CardWarsLossEXPModifier', '10'),
(67, 'Warchest', '0'),
(68, 'WarchestThreshold', '498'),
(69, 'CardWarsAttackCritChance', '2'),
(70, 'WeddingScript', 'We are gathered here today to wed %%GROOM%% and %%BRIDE%% in Moogle Matrimony. Since %%GROOM%% is a cheapskate, %%GROOM%% can\r\nonly offer %%BRIDE%% a crappy surname.  I now pronounce you Mr/Mrs and Mr/Mrs %%SURNAME%%.  A relog may be necessary for a surname change.'),
(71, 'RegistrationEmail', 'Welcome %%PLAYER%%,<BR>\r\n<BR>\r\nThank you for joining one of the biggest Triple Triad clones on the Internet where we have literally over 1,000 games played everyday.  You are only a few minutes from playing with fellow final fantasy and triple triad fans alike!<BR>\r\n<BR>\r\nThere are two different ways you can maintain your account and play Triple Triad Extreme.<BR>\r\n<BR>\r\n1) You can login to the portal by pointing your browser to http://www.tripletriadoffline.com/Portal/Login.aspx - you can do everything except chat and play the games at this website.  You can look up the 30+ decks, and 3500+ cards that we have, look up information about the game in the many wikis, or see where you stand against everyone else in the many leaderboards available on the portal.<BR>\r\n<BR>\r\n2) You can download the client at http://www.tripletriadforums.com/programs/TTESetup.exe - where you can login, chat, and play in real time in the game lobby with all the other dedicated Triple Triad Extreme players.<BR>\r\n<BR>\r\nYour Login Information:<BR>\r\n<BR>\r\nUsername: %%PLAYER%%<BR>\r\nPassword: %%PASSWORD%%<BR>\r\n<BR>\r\nSincerely,<BR>\r\nGM Atomicstorm<BR>'),
(72, 'WantedCardGoldMinimum', '30'),
(73, 'WantedCardFeePercentage', '0.05'),
(74, 'DailyJackpot', '40191.75'),
(75, 'WeeklyJackpot', '18117.75'),
(76, 'DailyJackpotRake', '0.25'),
(77, 'WeeklyJackpotRake', '0.25'),
(78, 'JackpotTicket', '2'),
(79, 'GuildCost', '5000'),
(80, 'ForumJackpot', '86033'),
(81, 'OfferJackpot', '0'),
(82, 'SurvivorID', '3963'),
(83, 'SurvivorMarkedPlayer', 'leoking18'),
(84, 'SurvivorStreak', '1'),
(85, 'ScratchProgressive', '723019');
