
-- --------------------------------------------------------

--
-- Table structure for table `guild_descriptions`
--

CREATE TABLE `guild_descriptions` (
  `guild` varchar(50) NOT NULL DEFAULT '',
  `description` varchar(2000) NOT NULL DEFAULT '',
  `motd` varchar(2000) NOT NULL DEFAULT '',
  `gold` int(10) UNSIGNED NOT NULL DEFAULT 0,
  `status` int(10) UNSIGNED NOT NULL DEFAULT 0,
  `cardcap` int(10) UNSIGNED NOT NULL DEFAULT 25,
  `creatorName` varchar(50) NOT NULL,
  `isDeleted` int(11) NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

--
-- Dumping data for table `guild_descriptions`
--

INSERT INTO `guild_descriptions` (`guild`, `description`, `motd`, `gold`, `status`, `cardcap`, `creatorName`, `isDeleted`) VALUES
('501st ', 'Welcome to the best guild ever\r\ngo to our official site \r\nwww.freewebs.com/tt501st', 'recruting now', 10, 0, 25, '', 0),
('Ad Arcana', 'Ancient Cartomancery.', 'Y hulo thar', 0, 0, 25, '', 0),
('Arcane Empire', 'Welcome to the Arcane Empire, where only the mysterious know of our existence. With our arcane powers, we will rule all over Dark Wind, in hopes to unify the community under our legacy. If you think you are capable of ruling DarkWind, PM Raid the_Emperor or any officers and they will guide you to our secret domain....', 'Ok everyone, Arodace has finally entered Arcane Empire and now things will be starting off properly. We have over 500 cards in our guild bank, and dont forget about depositing 10 gp every time you come on, so we can buy special cards, which will be deposited into the bank. Then you guys can borrow those special cards and once youve finished with it, you can just put it back for some other member to use. Thats all for today ^^\r\n\r\nArodace :)', 1, 0, 25, '', 0),
('Bell Guardians', 'Welcome to The Bell Guardians guild.\r\n\r\nThe Mystic Bell card have been stolen!\r\n\r\nVoices are telling that a tournament is going to start somewhere in the universe, and our mission, is to feat this evil player and give it back to the mystic prayer.\r\n\r\nTo feat, we will have to ground together.\r\n\r\nGood luck and get fun!', '', 0, 0, 25, '', 0),
('BloodBank', 'I\'ts my bank son', '', 0, 0, 25, '', 0),
('Caiman Land', 'Not for caimans only', '', 100000, 0, 25, '', 0),
('CC Group', 'Guild based off of the CC Group of FF8! Join and have a good time!\r\nOur guild board is almost finished!\r\nJoin our active guild for great benefits!', 'Stay active!', 16, 0, 25, '', 0),
('Chaos Order', 'Bringing order to chaos.\r\nCreating chaos from order.\r\nYou decide!\r\nApply now and make your choice!\r\nchaosorderguild@hotmail.com', 'Chaos Order taking DW by storm!\r\n\r\nChaos Order forum is now up!\r\nhttp://z10.invisionfree.com/Chaos_Order_Guild/index.php?\r\n\r\n\r\n\r\n- i back ! kam\r\n\r\nWelcome to CO Midgar and Replikant! - Drak', 0, 0, 25, '', 0),
('Dark Oblivion', '*sigh* Hai!!!!', 'All cards in the GB are mine so dont touch unless you ask me ', 0, 0, 25, '', 0),
('Da_Witnesses', 'Come one come all who wants to join the Congregation....', '', 0, 0, 25, '', 0),
('Deep  Dungeon', 'Alone in Deep Dungeon.', 'g', 0, 0, 25, '', 0),
('Enhasa', 'Named for the First City \r\nwithin The Kingdom of Zeal. \r\nChrono Trigger\r\n~Dark Ages\r\n\r\nFire Summons Wind, \r\nWind Makes Water Dance =D', 'La = Fire \r\nVos = Big\r\nC.T = The Bestest game of all Time ^^', 10500, 0, 210, '', 0),
('Eternal Mirage', 'a guild for cool peoples ', '', 0, 0, 50, '', 0),
('FBI: X-Files', 'I want to show you what is the reality. What you remember is only an illusion', '', 0, 0, 25, '', 0),
('FF_Ksenomorphs', 'Welcome to FF_Ksenomorphs\r\nWe are one of the fastest growing guilds in Dark Wind.\r\nMembers of FF_Ksenomorphs benefit from joining this guild because they meet new friends and together become great Triple Triad players :)\r\n', 'Hey there people! Were looking for great ideas so we can improve our guild even more!! :)\r\nSo dont be quiet and shout out ur ideas to the officers and try to find new members to make FF_Ksenomorphs an even better guild.\r\n\r\nWe should gather some GP in the guild bank. I reckon every member should put 10 GP everyday so we can get more money to buy Special Edition cards. \r\nAnyone who needs it temporarily can borrow it and then put it back in the guild bank so that other members can use it as well.\r\nAny questions about this PM Raid the_Emperor and Arodace zairath or any other officers.\r\nThanks!!! :)', 0, 0, 25, '', 0),
('for Him', 'John 3:16', '', 500, 0, 25, '', 0),
('Forest Owls', 'Were the Forest Owls!!\r\nThe first brazilian guild(or at least I think it is ^^ If Im wrong, tell me please)\r\nhttp://z12.invisionfree.com/forestowls', '', 0, 0, 25, '', 0),
('Foxhound', 'This guild is powered by Crono22002 and Solidsnake.\r\n\r\n', 'popo\r\nI Heart Foxhound :o by MonGay', 0, 0, 25, '', 0),
('Galbadia Garden', 'Galbadia Garden.', 'Theres no such thing as too cynical. Its called being dead.\n', 118, 0, 750, '', 0),
('GamesRadar', 'Hi, we are of GamesRadar forum', 'Incoming the 2nd tournament guys...', 0, 0, 25, '', 0),
('geo-stigma', 'we may be small but the sickness will infect everyone once we start taking over theres no point of fighting', 'get down with the sickness', 95, 0, 25, '', 0),
('Glance Reviver', 'Glance Reviver', '', 2500, 0, 25, '', 0),
('Glory', 'Guild', '', 0, 0, 25, '', 0),
('Gods of War', 'GoDz', '', 0, 0, 25, '', 0),
('GuitarAddicted', 'A oneman army xD\r\nJust to stor my cards and have fun with the game ;-)\r\nIf you wanna join just ask me special welcome are guitar players and  germans ;-)', '', 0, 0, 25, '', 0),
('Gurren Brigade', 'o.o', 'Orly', 0, 0, 25, '', 0),
('hates you!', '...', '', 0, 0, 25, '', 0),
('Haxxors rus', 'most any1 can join if they wish im not picky', 'i have to do my best in order to be the best.', 0, 0, 25, '', 0),
('Heavenly Heroes', 'Good decisions comes from experience but experience comes from bad choices. \r\n   People who learned from their mistakes were given a second chance. Theyve discovered their destiny.\r\n Are you willing to discover yours? \r\n', 'Welcome', 0, 0, 25, '', 0),
('Hell\'s Cavalry', 'Evil\'s Last Ride', '', 3000, 0, 25, '', 0),
('I am in a Guild', 'We are all in a guild!!!!!!17', 'If you are reading this, then you are in a guild!!!!!17', 0, 0, 25, '', 0),
('Illuminati', 'In preparation for something bigger and greater, we are preparing for The Great Battle, a battle against all other guilds for glory and honor.  We are making a compilation of the greatest players in hopes to dominate all other guilds.  Are you one of the greats?', '', 30000, 0, 285, '', 0),
('Jedi Masters', 'This is the guild of the Jedi Masters...an ancient order of the protectors of the Force', '\"The Force will be with you...always...', 0, 0, 25, '', 0),
('Kingdom Cards', 'Sora, Goofy and Donald sending greetings', '', 0, 0, 25, '', 0),
('Knights of Dawn', 'Revised form of my old guild but better than ever', '', 0, 0, 1065, '', 0),
('Knights Of Gaia', 'Gaia will thrive!!', '', 737, 0, 25, '', 0),
('Kogarasumaru', 'If youre reading this to try to learn bout Koga, then you havent been playing TTE long enough.\r\n\r\n\r\n~WhErE MaH DoGGs AT??!?! Srsly!! Wheres Crim?!?! BRs takin OVER!', 'Sandwiches that do not have a name attached are unofficially Ones.', 24459, 0, 25, '', 0),
('La Perla Negra', 'El clan del conocido pirata Jack Sparrow y su tripulacion. Al abordaje!', 'Recordamos al señor Jack Sparrow que me devuelva la pasta que me debe, Gañan! jajaja', 32, 0, 25, '', 0),
('Leading Edge', 'To drive harder and be the best (to be on the limit and to push it ahead).\r\n\r\nThe guild bank now has up to 3 of any particular card. This 3rd card is available and free for any active member. All you have to do is ask. ', 'have fun every1', 359, 0, 25, '', 0),
('Lighting Vortex', 'nothing special bout this guild,its just here\r\nif you have questions,i might have answer\r\n', 'you can put your unwanted cards in our guild bank', 0, 0, 25, '', 0),
('LOLGUILD', 'LOL', '', 0, 0, 25, '', 0),
('Master 360', 'Trusted family members only!!!\nCards: 1137 / 3593\nCard Ratio: 31.6%', 'Be honored!!!', 15129, 0, 1275, '', 0),
('Mogs n Moombas', 'Everything is fun and games to us  xxxKUPOxxx', '', 3100, 0, 275, '', 0),
('Negative Effect', 'WELCOME', 'you are talking to god plz leave a message after the beep', 170, 0, 25, '', 0),
('NERV Reborn', 'The once great guild of NERV is resurrected and reborn once more, here to take the world of darkwind by storm and show them that WE MEAN BUSINESS!!!\r\n\r\n\"Gods In His Heaven. Alls Right With The World\"', 'If Any Of You Break An Eva Unit..... For God Sakes Dont Just Hide It Under Your Bed, Come Tell Me So I Can Kill You Sooner Intead Of When The Knife Is Blunt...', 0, 0, 25, '', 0),
('Ninja pirates', 'AHOY! We are the sneakiest pirates in Dark Wind, we travel the seas stealing cards and swiping AP! Get cheap cards, if you join Guild bank available to all who get five members to join.', '', 0, 0, 25, '', 0),
('Nitro Circus', 'Best vodka drinkers ever. \nCome and join us . \nYo ho yo ho and a bottle of VODKA\nZigfrid and Aska', 'come and drink with us :D', 0, 0, 25, '', 0),
('operation BLACK', 'Leader: deadzone\r\nofficer1: cecil285\r\nofficer2: akesson\r\nofficer3\r\n------------- we now require 50gp each day.(officers do not need to they have  proven loyal) \r\n\r\n.\r\n', 'Become a officer!!! Donate to the guild , or get to know the officers\\gm and become one BUT REMEMBER! ONLY 3 PEOPLE WILL BE OFFICERS!!!\r\nTo become a officer you must donate regularly to the bank or make a big donation, and be a regular on the game. all officers are permitted to 1 card a day and cannot take another out unless the other is put back (unless i give the go ahead)', 0, 0, 25, '', 0),
('Operation Delta', 'Hey you wanna know about it ask me yourself', '', 0, 0, 25, '', 0),
('Organization 13', 'Apply if you wish to be included o.O', '?', 0, 0, 25, '', 0),
('OtherWorld', '...', 'ppl when you puts cards to Guild Bank , plz tell me this first!', 0, 0, 25, '', 0),
('Po Chi Lam', '3 friends addicted', '', 0, 0, 25, '', 0),
('Rally Cry', 'Public Message Board', '', 0, 0, 25, '', 0),
('Revival', ':-D', '', 0, 0, 25, '', 0),
('Ron Sons', 'Roooooooooooooon!!!', '', 0, 0, 25, '', 0),
('Secret service', 'im in disguise', '', 0, 0, 25, '', 0),
('SeeD', 'SeeD is a unique mercenary guild where members work as a team to become the best in Darkwind. There is no greediness allowed and everyone works together to improve each others skills.', 'Im kupo for kupo nuts!!', 0, 0, 25, '', 0),
('Servants of Darkness', 'GM Guild', 'Gms Unite', 12, 0, 25, '', 0),
('Sexy Angels', 'hehehehe we are all sexy peoples', 'live life as if its your last day', 0, 0, 25, '', 0),
('Shadowbugs', 'We make decks,complete decks,beat ranks and alot more\nWere open for all just pm one of the Officers or Guild Master and ask and they will consider it.\n\nAssociated with GKP', 'whoopie', 0, 0, 585, '', 0),
('Spirit of Chaos', ' \"When people tell me \"plz\" just because its shorter than \"please\", I feel perfectly justified to answer \"No\" because its shorter than \"Yes\" \" ', '', 0, 0, 25, '', 0),
('SupremoS', 'Daiana Sos El Amor De Mi Vida Te Amo Con Todo Mi Corazon', '', 0, 0, 25, '', 0),
('Terror Squad', 'Welcome to the terror world.......\r\n                                                       Guild speciality\r\nWe r the largest guild in this whole game DW\r\n', 'be happy play well....', 0, 0, 25, '', 0),
('The Coop', 'Where the Chickens go.', '', 0, 0, 25, '', 0),
('The Elite', 'My New Guild,Have Fun and Happy GamingWe Have won 1 tournament so far!!', 'happy gaming!!', 1250, 0, 25, '', 0),
('The Harem', 'Come join my harem and help me make it into the sexiest and most talented guild out there. My slaves and/or females only.', '.', 0, 0, 25, '', 0),
('ThE ME INC', 'The Enemy Of The Enemy Is Still The Enemy.', 'Dont Forget To Brush Your Teeth & Eat Your Vegetables!!!!', 0, 0, 25, '', 0),
('The One', 'I Walk Alone', '', 0, 0, 25, '', 0),
('Timber Maniacs', 'The ultimate guild from deep forests of Timber. Attaching our playing skill for ages, we are here to take final challange. Only russian players are addicted.', '', 0, 0, 25, '', 0),
('Triad Masters', 'A Guild for the storngest Warriors of Triad', '', 0, 0, 25, '', 0),
('Trodain Empire', '- We are recruiting players with high winning% as well as high rankings. If you are accepted, consider yourself one of the best in the game.\r\n\r\n- If any member is accepted into the guild, they will receive immediatly one lvl 10 card from the guild bank.\r\n\r\n- Please check the \"Guild Menber Rewards\" forum for a list of potential monthly rewards.\r\n\r\n- All guild members are to be respectful to all TTE players (no matter how much you dislike someone.... keep it to yourself).\r\n\r\n- Act with integrity and good character (just because others act like they are five years old doesnt mean we have to play along).', 'Check out our new (Updated) Guild Forum: http://trodianempire.bigforumpro.com\r\n\r\nThere have been many changes.... please leave your suggestions in the suggestion box.\r\n\r\nMany guild rules will be changing (for the better).  Please visit the forums frequently to stay updated.\r\n\r\nPM me if you have any questions or concerns\r\n\r\n\r\n\r\n\r\n\r\n', 85000, 0, 1090, '', 0),
('Ultima', 'Good game is more valuable than a good card', '', 40254, 0, 70, '', 0),
('UltimaCloud', 'He\'s Back D', '', 541, 0, 25, '', 0),
('Ultimate Chaos', 'I\'ll  leave this for mini to edit later', '', 0, 0, 625, '', 0),
('We The People', 'Knights from the Ice Planet; Pluto.\nWe counting all kinds of funny coloured money over here. We rule your galaxy.\n\nWe aint lyin - If your sellin, we aint buying, All the cards on your block, best believe we supplyin.\n\nIn Cahoots with the following; Somalian Pirates, Arabian Pirates and any other Pirate related groups.', 'Ali Baba and the 40 Thieves in the Modern Era, you in? \n\nmdemaz2 says out of character, \" our hood aint compton its pluto, dont wear armour we wear kefvlar while doing ju-do \" Iced planet ffs.\n\nlol skemz-\n-- &amp;amp;amp;lt;Bank&amp;amp;amp;gt;  350 GP was added to the guild bank. 02:52:01 -- FFS, not forgetting my duties as PK officer. Slithered.\n\nHere I go again &amp;lt;Bank&amp;gt;  350 GP was added to the guild bank. 09:13:56. Slithered. \n------ Hey peeps, this is  just a reminder for officers who still make the 350gp donation. --- <Bank>  5375 GP was added to the guild bank. 19:30:10 Thats for the loan I took, +7.5% recharge, lemme know if its more... Slithered.', 0, 0, 5665, '', 0),
('Wikas Whanau', 'Where Friends of Wikaitaia gather', '', 0, 0, 570, '', 0);
