
-- --------------------------------------------------------

--
-- Table structure for table `trophies`
--

CREATE TABLE `trophies` (
  `ID` int(10) UNSIGNED NOT NULL,
  `TrophyName` varchar(45) NOT NULL,
  `TrophyDescription` varchar(300) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci ROW_FORMAT=COMPACT;

--
-- Dumping data for table `trophies`
--

INSERT INTO `trophies` (`ID`, `TrophyName`, `TrophyDescription`) VALUES
(1, 'Voted 2009 Best OTT Player', '2009 Triple Triad Extreme Community Vote Award'),
(2, 'Voted 2009 Best TT Player', '2009 Triple Triad Extreme Community Vote Award'),
(3, 'Voted 2009 Best TTM Player', '2009 Triple Triad Extreme Community Vote Award'),
(4, 'Voted 2009 Best Sphere Break Player', '2009 Triple Triad Extreme Community Vote Award'),
(5, 'Voted 2009 Best Team Player', '2009 Triple Triad Extreme Community Vote Award'),
(6, 'Voted 2009 Funniest Player', '2009 Triple Triad Extreme Community Vote Award'),
(7, 'Voted 2009 Best Male Player', '2009 Triple Triad Extreme Community Vote Award'),
(8, 'Voted 2009 Best Female Player', '2009 Triple Triad Extreme Community Vote Award'),
(9, 'Voted 2009 Most Addicted Player', '2009 Triple Triad Extreme Community Vote Award'),
(10, 'Voted 2009 Most Supportive Player', '2009 Triple Triad Extreme Community Vote Award'),
(11, 'Voted 2009 Most Helpful', '2009 Triple Triad Extreme Community Vote Award'),
(12, 'Voted 2009 Most Helpful GM', '2009 Triple Triad Extreme Community Vote Award'),
(13, 'Voted 2009 Best Up and Coming Player', '2009 Triple Triad Extreme Community Vote Award'),
(14, 'Voted 2009 Best Sportsmanship', '2009 Triple Triad Extreme Community Vote Award'),
(15, 'Voted 2009 Best Player Name', '2009 Triple Triad Extreme Community Vote Award'),
(16, 'Voted 2009 Most Annoying', '2009 Triple Triad Extreme Community Vote Award'),
(17, 'Voted 2009 Most Noobish', '2009 Triple Triad Extreme Community Vote Award'),
(18, 'Voted 2009 Best Graphical Artist', '2009 Triple Triad Extreme Community Vote Award'),
(19, 'Voted 2009 Worst Loser', '2009 Triple Triad Extreme Community Vote Award'),
(20, 'Voted 2009 Most Unsung', '2009 Triple Triad Extreme Community Vote Award'),
(21, 'Voted 2009 Best Merchant', '2009 Triple Triad Extreme Community Vote Award'),
(22, 'Voted 2009 Favorite Oldie', '2009 Triple Triad Extreme Community Vote Award'),
(23, 'Voted 2009 Best Hair', '2009 Triple Triad Extreme Community Vote Award'),
(24, 'Voted 2009 Player with Best Gaming Area', '2009 Triple Triad Extreme Community Vote Award'),
(25, 'February 2009 ToC Champion', 'Winner of the February, 2009 Tournament of Champions Tournament'),
(26, 'March 2009 ToC Champion', 'Winner of the March, 2009 Tournament of Champions Tournament'),
(27, 'August 2009 3rd Place Tournament of Champions', 'August 2009 3rd Place Tournament of Champions'),
(28, 'August 2009 2nd Place Tournament of Champions', 'August 2009 2nd Place Tournament of Champions'),
(29, 'August 2009 1st Place Tournament of Champions', 'August 2009 1st Place Tournament of Champions'),
(30, 'Speed Completion Award: Anime', 'Speed Completion Award: Anime Deck'),
(31, 'Speed Completion Award: Anime2', 'Speed Completion Award: Anime 2 Deck'),
(32, 'Speed Completion Award: CC', 'Speed Completion Award: Chrono Cross Deck'),
(33, 'Speed Completion Award: Crusade', 'Speed Completion Award: Chrono Crusade Deck'),
(34, 'Speed Completion Award: DQ8', 'Speed Completion Award: Dragon Quest 8 Deck'),
(35, 'Speed Completion Award: FF6', 'Speed Completion Award: Final Fantasy 6 Deck'),
(36, 'Speed Completion Award: FF7', 'Speed Completion Award: Final Fantasy 7 Deck'),
(37, 'Speed Completion Award: FF9', 'Speed Completion Award: Final Fantasy 9 Deck'),
(38, 'Speed Completion Award: FFAC', 'Speed Completion Award: Final Fantasy: Advent Children Event Deck'),
(39, 'Speed Completion Award: FFT', 'Speed Completion Award: Final Fantasy Tactics Deck'),
(40, 'Speed Completion Award: FFTA', 'Speed Completion Award: Final Fantasy Tactics Advanced Deck'),
(41, 'Speed Completion Award: FFX', 'Speed Completion Award: Final Fantasy X Deck'),
(42, 'Speed Completion Award: FFXII', 'Speed Completion Award: Final Fantasy XII Deck'),
(43, 'Speed Completion Award: FireEmblem', 'Speed Completion Award: Fire Emblem Deck'),
(44, 'Speed Completion Award: Halloween', 'Speed Completion Award: Halloween Holiday Event Deck'),
(45, 'Speed Completion Award: Johto', 'Speed Completion Award: Johto Pokemon Deck'),
(46, 'Speed Completion Award: Kanto', 'Speed Completion Award: Kanto Pokemon Deck'),
(47, 'Speed Completion Award: KingdomHearts', 'Speed Completion Award: Kingdom Hearts Deck'),
(48, 'Speed Completion Award: Legends', 'Speed Completion Award: Legends Deck'),
(49, 'Speed Completion Award: Nintendo', 'Speed Completion Award: Nintendo Deck'),
(50, 'Speed Completion Award: NXC', 'Speed Completion Award: Namco vs. Capcom Deck'),
(51, 'Speed Completion Award: Sega', 'Speed Completion Award: Sega Deck'),
(52, 'Speed Completion Award: SMT', 'Speed Completion Award: Shin Megami Tensei Deck'),
(53, 'Speed Completion Award: Standard', 'Speed Completion Award: Final Fantasy 8 Deck'),
(54, 'Speed Completion Award: Suikoden2', 'Speed Completion Award: Suikoden 2 Deck'),
(55, 'Speed Completion Award: Suikoden3', 'Speed Completion Award: Suikoden 3 Deck'),
(56, 'Speed Completion Award: XenoTrigger', 'Speed Completion Award: Xeno Trigger Deck'),
(57, 'Speed Completion Award: Valentines', 'Speed Completion Award: Valentines Holiday Event Deck'),
(58, 'Speed Completion Award: Suikoden1', 'Speed Completion Award: Suikoden 1 Deck'),
(59, 'Speed Completion Award: MarvelDC', 'Speed Completion Award: Marvel vs DC Comics'),
(60, 'Speed Completion Award: GodofWar', 'Speed Completion Award: God of War'),
(61, 'Speed Completion Award: Lenneth', 'Speed Completion Award: Valkyrie Profile: Lenneth'),
(62, 'Speed Completion Award: Summer', 'Speed Completion Award: Extreme Summer'),
(63, 'Speed Completion Award: Christmas', 'Speed Completion Award: Christmas Event Deck'),
(64, 'Speed Completion Award: DuelMonsters', 'Speed Completion Award: Duel Monsters Deck'),
(65, 'Speed Completion Award: FF3', 'Speed Completion Award: Final Fantasy 3 Deck'),
(93, 'Sept 2009 3rd Place Tournament of Champions', 'September 2009 3rd Place Tournament of Champions'),
(94, 'Sept 2009 2nd Place Tournament of Champions', 'September 2009 2nd Place Tournament of Champions'),
(95, 'Sept 2009 1st Place Tournament of Champions', 'September 2009 1st Place Tournament of Champions'),
(96, 'Speed Completion Award: Halloween2009', 'Speed Completion Award: Halloween 2009 Deck'),
(97, 'Speed Completion Award: MegamanZero', 'Speed Completion Award: Megaman Zero Deck'),
(98, 'Speed Completion Award: Hoenn', 'Speed Completion Award: Hoenn Deck'),
(99, 'Speed Completion Award: WorldofWarcraft', 'Speed Completion Award: World of Warcraft Deck'),
(100, 'Speed Completion Award: Christmas2009', 'Speed Completion Award: Christmas 2009 Deck'),
(101, 'Speed Completion Award: WorldofMana', 'Speed Completion Award: World of Mana Genesis Deck'),
(102, 'Nov 2009 1st Place Tournament of Champions', 'November 2009 1st Place Tournament of Champions'),
(103, 'Jan 2010 1st Place Tournament of Champions', 'January 2010 1st Place Tournament of Champions'),
(104, 'Jan 2010 2nd Place Tournament of Champions', 'January 2010 2nd Place Tournament of Champions'),
(105, 'Jan 2010 3rd Place Tournament of Champions', 'January 2010 3rd Place Tournament of Champions'),
(106, 'Speed Completion Award: Valentines2010', 'Speed Completion Award: Valentines 2010 Deck'),
(107, 'Speed Completion Award: Summer 2010', 'Speed Completion Award: Summer 2010 Deck'),
(108, 'Speed Completion Award: TTE 10th', 'Speed Completion Award: TTE 10th Anniversary Deck'),
(109, 'Speed Completion Award: Odin Sphere', 'Speed Completion Award: Odin Sphere Deck'),
(110, 'Speed Completion Award: CLAMP', 'Speed Completion Award: CLAMP Deck'),
(111, 'Speed Completion Award: Digimon Destiny', 'Speed Completion Award: Digimon Destiny Deck'),
(112, 'Speed Completion Award: FF2', 'Speed Completion Award: Final Fantasy 2 Deck'),
(113, 'Speed Completion Award: FF4', 'Speed Completion Award: Final Fantasy 4 Deck'),
(114, 'Speed Completion Award: Christmas2010', 'Speed Completion Award: Christmas 2010 Deck'),
(115, 'Voted 2010 Best Triple Triad Player', '2010 Triple Triad Extreme Community Award'),
(116, 'Voted 2010 Best Omni Triple Triad Player', '2010 Triple Triad Extreme Community Award'),
(117, 'Voted 2010 Best Triple Triad Memory Player', '2010 Triple Triad Extreme Community Award'),
(118, 'Voted 2010 Best Sphere Break Player', '2010 Triple Triad Extreme Community Award'),
(119, 'Voted 2010 Best Triple Triad War Player', '2010 Triple Triad Extreme Community Award'),
(120, 'Voted 2010 Best Team Player', '2010 Triple Triad Extreme Community Award'),
(121, 'Voted 2010 Best Sportsman', '2010 Triple Triad Extreme Community Award'),
(122, 'Voted 2010 Funniest Player', '2010 Triple Triad Extreme Community Award'),
(123, 'Voted 2010 Best Male Player', '2010 Triple Triad Extreme Community Award'),
(124, 'Voted 2010 Best Female Player', '2010 Triple Triad Extreme Community Award'),
(125, 'Voted 2010 Most Addicted Player', '2010 Triple Triad Extreme Community Award'),
(126, 'Voted 2010 Most Competitive Player', '2010 Triple Triad Extreme Community Award'),
(127, 'Voted 2010 Most Influential Player', '2010 Triple Triad Extreme Community Award'),
(128, 'Voted 2010 Most Supportive Player', '2010 Triple Triad Extreme Community Award'),
(129, 'Voted 2010 Most Helpful Administrator', '2010 Triple Triad Extreme Community Award'),
(130, 'Voted 2010 Best Up and Coming Player', '2010 Triple Triad Extreme Community Award'),
(131, 'Voted 2010 Biggest Troll', '2010 Triple Triad Extreme Community Award'),
(132, 'Voted 2010 Biggest Spammer', '2010 Triple Triad Extreme Community Award'),
(133, 'Voted 2010 Best Player\'s Username', '2010 Triple Triad Extreme Community Award'),
(134, 'Voted 2010 Best Graphical Artist', '2010 Triple Triad Extreme Community Award'),
(135, 'Voted 2010 Most Unsung', '2010 Triple Triad Extreme Community Award'),
(136, 'Voted 2010 Best Merchant', '2010 Triple Triad Extreme Community Award'),
(137, 'Voted 2010 Favorite Oldbie', '2010 Triple Triad Extreme Community Award'),
(138, 'Voted 2010 Most Helpful Player', '2010 Triple Triad Extreme Community Award'),
(139, 'Speed Completion Award: Summer2011', 'Speed Completion Award: Summer 2011'),
(140, 'Voted 2010 Best Overall Player', '2010 Triple Triad Extreme Community Award'),
(141, 'Feb 2010 1st Place Tournament of Champions', 'February 2010 1st Place Tournament of Champions'),
(142, 'July 2011 1st Place Tournament of Champions', 'July 2011 1st Place Tournament of Champions'),
(143, 'July 2011 2nd Place Tournament of Champions', 'July 2011 2nd Place Tournament of Champions'),
(144, 'July 2011 3rd Place Tournament of Champions', 'July 2011 3rd Place Tournament of Champions'),
(145, 'Speed CompletionAward: Halloween2011 Deck', 'Speed Completion Award: Halloween 2011'),
(146, 'Speed Completion Award: FF5', 'Speed Completion Award: Final Fantasy 5');
