
-- --------------------------------------------------------

--
-- Table structure for table `products`
--

CREATE TABLE `products` (
  `ID` int(10) UNSIGNED NOT NULL,
  `ProductName` varchar(150) NOT NULL,
  `ProductDescription` varchar(1000) NOT NULL,
  `ProductKeyword` varchar(50) NOT NULL,
  `ProductCost` varchar(10) NOT NULL,
  `ItemName` varchar(100) NOT NULL,
  `Subscription` int(10) UNSIGNED NOT NULL DEFAULT 0,
  `OneTime` int(10) UNSIGNED NOT NULL DEFAULT 1,
  `ItemType` varchar(45) DEFAULT NULL,
  `ItemDescription` varchar(1000) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci ROW_FORMAT=COMPACT;

--
-- Dumping data for table `products`
--

INSERT INTO `products` (`ID`, `ProductName`, `ProductDescription`, `ProductKeyword`, `ProductCost`, `ItemName`, `Subscription`, `OneTime`, `ItemType`, `ItemDescription`) VALUES
(1, 'Power User Membership', '<p><strong>Power User Membership Benefits Include:</strong></p><ul><li>10000 Gold</li><li>10000 Active Points</li><li>70% Gold at the End of Each Game</li><li>50% Experience at the End of Each Game</li><li>4 Tokens (Can Be Redeemed for Special Edition Cards)</li><li>Veteran Experience for Special Advancements</li><li>In-Game Recognition (Name Shows Up in Red on Login)</li><li>+60 Shop Bonus</li><li>100% Shop Rake Reduction</li><li>1 Random Loot Card Under $4.00</li><li>Partially Qualifies for the VIP Membership Trigger</li></ul>', 'MEMPU01', '20', 'Power User Membership', 1, 1, 'Memberships', 'The power user membership is the top tier of memberships and is a pre-requisite to triggering the VIP reward. <a class=\"toolTrigger\">Learn More</a>.'),
(2, 'Diamond Membership', '<p><strong>Diamond Membership Benefits Include:</strong></p><ul><li>7000 Gold</li><li>7000 Active Points</li><li>30% Gold at the End of Each Game</li><li>25% Experience at the End of Each Game</li><li>4 Tokens (Can Be Redeemed for Special Edition Cards)</li><li>Veteran Experience for Special Advancements</li><li>In-Game Recognition (Name Shows Up in Blue on Login)</li><li>+25 Shop Bonus</li><li>70% Shop Rake Reduction</li><li>1 Random Loot Card Under $2.00</li></ul>', 'MEMDMD01', '15', 'Diamond Membership', 1, 1, 'Memberships', 'The diamond membership is tier 3 of 4 of memberships offered. <a class=\"toolTrigger\">Learn More</a>.'),
(3, 'Platinum Membership', '<p><strong>Platinum Membership Benefits Include:</strong></p><ul><li>4000 Gold</li><li>4000 Active Points</li><li>10% Gold at the End of Each Game</li><li>10% Experience at the End of Each Game</li><li>2 Tokens (Can Be Redeemed for Special Edition Cards)</li><li>Veteran Experience for Special Advancements</li><li>In-Game Recognition (Name Shows Up in Platinum/Silver on Login)</li><li>+15 Shop Bonus</li><li>40% Shop Rake Reduction</li></ul>', 'MEMPLAT01', '10', 'Platinum Membership', 1, 1, 'Memberships', 'The platinum membership is tier 2 of 4 of memberships offered. <a class=\"toolTrigger\">Learn More</a>.'),
(4, 'Gold Membership', '<p><strong>Gold Membership Benefits Include:</strong></p><ul><li>2000 Gold</li><li>2000 Active Points</li><li>5% Gold at the End of Each Game</li><li>5% Experience at the End of Each Game</li><li>1 Token (Can Be Redeemed for Special Edition Cards)</li><li>Veteran Experience for Special Advancements</li><li>In-Game Recognition (Name Shows Up in Gold on Login)</li><li>+10 Shop Bonus</li><li>20% Shop Rake Reduction</li></ul>', 'MEMGLD01', '5', 'Gold Membership', 1, 1, 'Memberships', 'The gold membership is tier 1 of 4 of memberships offered. <a class=\"toolTrigger\">Learn More</a>.'),
(7, '5000 Gold Pack', '<p><strong>5,000 Gold Pack</strong></p><p>Gold/GP is the currency for everything in Triple Triad Extreme. This item is for 5,000 Gold only.</p>', 'GOLD5000PK', '6.99', '5000 Gold Pack', 0, 1, 'Currency', 'This awards 5,000 gold to the player for use in Triple Triad Extreme.'),
(8, '1000 Gold Pack', '<p><strong>1,000 Gold Pack</strong></p><p>Gold/GP is the currency for everything in Triple Triad Extreme. This item is for 1,000 Gold only. There is a microtransaction surcharge on this item of 50 cents per 1000 gold. For more than 1,000 Gold, see additional gold options.</p>', 'GOLD1000PK', '1.99', '1000 Gold Pack', 0, 1, 'Currency', 'This awards 1,000 gold to the player for use in Triple Triad Extreme.'),
(9, '10000 Active Points', '<p><strong>10,000 Active Points Pack</strong></p><p>Active Points are the currency for all side games in Triple Triad Extreme. This grants the player 10,000 active points.</p>', 'AP10000PK', '3.99', '10000 Active Points Pack', 0, 1, 'Currency', 'This awards 10,000 active points to the player for use in side-games and Chinchirorin wagers.'),
(10, '2500 Active Points', '<p><strong>2,500 Active Points Pack</strong></p><p>Active Points are the currency for all side games in Triple Triad Extreme. This grants the player 2,500 active points.</p>', 'AP2500PK', '0.99', '2500 Active Points Pack', 0, 1, 'Currency', 'This awards 2,500 active points to the player for use in side-games and Chinchirorin wagers.'),
(11, '500 Crystals Pack', '<p><strong>500 Crystals</strong></p><p>Grants the player 500 crystals for each pack purchased.</p>', 'CRY500', '5', '500 Crystals', 0, 1, 'Currency', 'Deposit 500 crystals in the player\'s account. This may be used to purchase cards, currency, or even memberships.'),
(12, 'Donation to the USO', '<p><strong>Donation to USO</strong></p><p><table border=0 width=\"300px\"><tr><td><img src=\"http://www.tripletriadextreme.com/Handlers/CardBuilder.ashx?color=blue&cardname=Purple%20Heart\"></td><td>Grants the player the Purple Heart special edition card and feat of strength achievement for the non-tax-deductible donation.</p></td></tr></table>', 'CHARITYUSO', '10', 'Donation to the USO', 0, 1, 'SpecialInterest', 'Give a donation to the <a href=\"http://www.uso.org\" target=\"_new\">USO</a> and receive the Purple Heart special-edition card. <a class=\"toolTrigger\">Learn More</a>.'),
(13, 'Donation to the Charity Water', '<p><strong>Donation to Charity Water</strong></p><p><table border=0 width=\"300px\"><tr><td><img src=\"http://www.tripletriadextreme.com/Handlers/CardBuilder.ashx?color=blue&cardname=Niagara%20Falls\"></td><td>Grants the player the Niagara Falls special edition card and feat of strength achievement for the non-tax-deductible donation.</p></td></tr></table>', 'CHARITYNIAGARA', '10', 'Donation to Charity Water', 0, 1, 'SpecialInterest', 'Give a donation to Charity Water and receive the Niagara Falls special-edition card. <a class=\"toolTrigger\">Learn More</a>.'),
(14, 'Donation to the Red Cross', '<p><strong>Donation to the Red Cross</strong></p><p><table border=0 width=\"300px\"><tr><td><img src=\"http://www.tripletriadextreme.com/Handlers/CardBuilder.ashx?color=blue&cardname=Red%20Cross\"></td><td>Grants the player the Red Cross special edition card and feat of strength achievement for the non-tax-deductible donation.</p></td></tr></table>', 'CHARITYRC', '10', 'Donation to the Red Cross', 0, 1, 'SpecialInterest', 'Give a donation to the Red Cross and recieve the Red Cross special-edition card. <a class=\"toolTrigger\">Learn More</a>.'),
(15, 'Donation to the Japan Relief Efforts', '<p><strong>Donation to Mount Fuji</strong></p><p><table border=0 width=\"300px\"><tr><td><img src=\"http://www.tripletriadextreme.com/Handlers/CardBuilder.ashx?color=blue&cardname=Mount%20Fuji\"></td><td>Grants the player the Mount Fuji special edition card and feat of strength achievement for the non-tax-deductible donation.</p></td></tr></table>', 'CHARITYJRE', '10', 'Donation to the Japan Relief Efforts', 0, 1, 'SpecialInterest', 'Give a donation to the Japan Relief Efforts and recieve the Mount Fuji special-edition card. <a class=\"toolTrigger\">Learn More</a>.'),
(16, 'Weekend Pass, Diamond Membership', '<br /><strong>2 Day Pass, Diamond Membership</strong><br />\r\nWant to give a membership a whirl but don\'t want to pay much money? You can now get a diamond membership for 2 days to see how memberships affect you. Weekend passes do not get all the benefits of the full month memberships.<br />\r\n<br />\r\nDiamond Membership Benefits Include:<br />\r\n<br />\r\n2500 Active Points<br />\r\n30% Gold at the End of Each Game<br />\r\n25% Experience at the End of Each Game<br />\r\nVeteran Experience for Special Advancements<br />\r\nIn-Game Recognition (Name Shows Up in Blue on Login)<br />\r\n+25 Shop Bonus<br />\r\n70% Shop Rake Reduction<br />', 'WKENDDM01', '3.99', 'Triple Triad Extreme: Weekend Pass Diamond Membership', 0, 1, NULL, NULL);
