
-- --------------------------------------------------------

--
-- Table structure for table `ott_temp_gamecards`
--

CREATE TABLE `ott_temp_gamecards` (
  `GameID` int(10) NOT NULL,
  `PlayerType` int(2) DEFAULT NULL,
  `Player_Hand_0` varchar(60) DEFAULT NULL,
  `Player_Hand_1` varchar(60) DEFAULT NULL,
  `Player_Hand_2` varchar(60) DEFAULT NULL,
  `Player_Hand_3` varchar(60) DEFAULT NULL,
  `Player_Hand_4` varchar(60) DEFAULT NULL,
  `Player_Hand_5` varchar(60) DEFAULT NULL,
  `Player_Hand_6` varchar(60) DEFAULT NULL,
  `Player_Hand_7` varchar(60) DEFAULT NULL,
  `Player_Hand_8` varchar(60) DEFAULT NULL,
  `Player_Hand_9` varchar(60) DEFAULT NULL,
  `Player_Hand_10` varchar(60) DEFAULT NULL,
  `Player_Hand_11` varchar(60) DEFAULT NULL,
  `Player_Hand_12` varchar(60) DEFAULT NULL,
  `Player_Hand_13` varchar(60) DEFAULT NULL,
  `Player_Hand_14` varchar(60) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

--
-- Dumping data for table `ott_temp_gamecards`
--

INSERT INTO `ott_temp_gamecards` (`GameID`, `PlayerType`, `Player_Hand_0`, `Player_Hand_1`, `Player_Hand_2`, `Player_Hand_3`, `Player_Hand_4`, `Player_Hand_5`, `Player_Hand_6`, `Player_Hand_7`, `Player_Hand_8`, `Player_Hand_9`, `Player_Hand_10`, `Player_Hand_11`, `Player_Hand_12`, `Player_Hand_13`, `Player_Hand_14`) VALUES
(2811469, 2, 'GIM47N', '', '', '', '', '', '', '', '', '', 'Biyomon', 'Gekomon', 'Nyaromon', 'Yuramon', 'Tokomon'),
(2811469, 1, '', '', '', '', '', '', '', '', '', '', 'Gremlin', 'Valron', 'Touch Me', '2 Faced', 'Haruka Urashima'),
(2811470, 1, '', '', '', '', '', '', '', '', '', '', 'Rasler', 'Grenade', 'Piranha', 'Aries', 'Lone Wolf'),
(2811470, 2, '', '', '', '', '', '', '', '', '', 'Skeleton', '', 'Ogre', 'Yan', 'Stealth Behemoth', 'Hedgehog Pie'),
(2811471, 1, '', '', '', '', '', '', '', '', '', 'Skeleton', 'Baku', 'Ogre', 'Yan', 'Stealth Behemoth', 'Hedgehog Pie'),
(2811471, 2, '', '', '', '', '', '', '', '', '', 'Tri-Face', 'Rasler', 'Grenade', 'Piranha', 'Aries', 'Lone Wolf'),
(2811479, 2, '', '', '', '', '', '', '', '', '', '', 'FF5 Kelgar', 'Solon', 'Esper Tritoch', 'Tina Armstrong', 'Golbat'),
(2811479, 1, '', '', '', '', '', '', '', '', '', '', 'Mt Hobbs Gargoyle', 'The Change', 'Dixie Kong', 'Turbo Synchron', 'Tir Mcdohl'),
(2811481, 1, '', 'Kel-Thuzad', 'Zouchouten', 'Kuromimi', 'Chocobo Eater', 'Summer Balthier', 'Diresaur', 'Plant Brain', 'Ull', 'Hoppip', 'FF5 Byurobolos', 'Amnennar The Coldbringer', 'Raichu', 'Astral Amulet', 'Bishop Luc'),
(2811481, 2, '', 'FF5 Boco', 'King Trode', 'Mitsuru Kijiro', 'Kino', 'Aeon Mindy', 'Supergirl', 'Banes Venom', 'Plant Brain', 'Nefarian', 'Guardian Thor', 'Jasmine', 'Braskas Final Aeon', 'Kiba', 'Scarecrow'),
(2811482, 2, 'Reaper of the Cards', 'Ed', 'FF5 Sylph', 'Reiji', 'Phrekyos', 'Purple Pikmin', 'The Ouzu', 'FF5 Kestrel', 'Kingu', 'Pink Yoshi', 'Red Dragon', 'Village Oracle', 'Sergeant', 'Esper Ifrit', 'Strider Hiryuu'),
(2811482, 1, 'Baron Adamantoise', 'FF5 King Walse', 'EH Thunder Giant', 'Nefarian', 'For Dalmasca', 'Rainbow Devil', 'Marco', 'General Zod', 'Joey Wheeler', 'AL Blanche', 'Final Form', 'Parrot Dragon', 'Margie', 'General Vezax', 'Lump Wizard'),
(2811484, 1, '', '', 'Dullahan', 'Shara', 'Dracula', 'Sarah', 'Aeris', 'Chocobo Farm', 'AC Aeris', 'Hoi', 'Farina', 'Misses Jean', 'Stantlers Guidance', 'Barashim', 'Jack Skellington'),
(2811484, 2, '', '', 'FF5 Unknown Slime', 'Flyguy', 'Mediator Male', 'Talim', 'Tzenker', 'Bishop Luc', 'Love Triangle', 'Steamed Crab', 'Chinchou', 'The Move', 'Granaldo', 'Ogre', 'Sothe'),
(2811486, 2, '', '', '', '', '', '', '', '', '', '', 'Prison Cage', 'Harle', 'Spiritual Concentration', 'Mina', 'Divermon'),
(2811486, 1, '', '', '', '', '', '', '', '', '', '', 'Algol', 'Moon Knight', 'FF5 Byurobolos', '2 Faced', 'Mina'),
(2811496, 1, '', '', '', '', '', '', '', '', '', '', 'Test Tiger', 'Donald and Daisy', 'Seaking', 'FF5 Tzuze', 'Powerful Red Dragon'),
(2811496, 2, '', '', '', '', '', '', '', '', '', '', 'La Mariposa', 'TestCard1', 'Loki', 'Beast', 'The Fly'),
(2812716, 1, '', 'Umi Ryuuzaki', 'Tata', 'Grat', 'Blue Eyes Toon Dragon', 'Rude', 'Team Rocket', '7 Colored Fish', 'Petal', 'Tzenker', 'Carlito', 'Cyber Nurse Green', 'Gold Warrior', 'Zagato', 'Morgan'),
(2812716, 2, '', 'FF5 Blue Dragon', 'Arwing', 'Victreebel', 'Black Frost', 'Red Eyes Black Dragon', 'Zagato', 'Cyclops Desert King', 'Sarasvati', 'Aeon Valefor', 'Nitrus Brio', 'Yanma', 'Old Man', 'Atroposis', 'Gogh'),
(2812737, 2, '', '', '', '', '', '', '', '', '', '', 'Kotaro', 'Bikini Rydia', 'Elekid', 'Squire Female', 'Bikini Jessica Albert'),
(2812737, 1, '', '', '', '', '', '', '', '', '', '', 'Cyber Nurse Gold', 'Calm Ace', 'Izlude Tingel', 'Devil Wolf', 'Poshul'),
(2812745, 1, '', '', 'Illumise', 'Blue Eyes Toon Dragon', 'Kurt Zisa', 'Persian', 'Final Rest', 'Colossus', 'FF5 Chocobo Party', 'Lips', 'Thrall', 'Minoru Kokubunji', 'Blazin Flizard', 'Merman', 'RBcard5'),
(2812745, 2, '', '', 'Esper Alexander', 'Gazimon', 'Yui', 'Marth', 'Flounder', 'Wolf Lord', 'Bishamon', 'Blizzard the Far North', 'Deep Dive', 'Cow', 'Clay Golem', 'Sabretooth', 'Larvae Moth'),
(2812752, 2, '', '', '', '', '', '', '', '', '', '', 'Rutee', 'Jimmy Olsen', 'Ingvar The Plunderer', 'The Time', 'FF5 Bomb'),
(2812752, 1, '', '', '', '', '', '', '', '', '', '', 'Metarook', 'Berri', 'Dusk', 'Couerl', 'Hammer Frame'),
(2812757, 2, '', 'Evil Eye', 'Billy Hatcher', 'Biggs', 'Soren', 'Raichu', 'Caverns Mind Flayer', 'Twilight Thorn', 'Strategist Albert', 'Poron', 'Skiploom', 'Velvet', 'The Watch of Life', 'Karen', 'Adamantai'),
(2812757, 1, '', '', 'Goofy', 'Glalie', 'Rockbomb', 'Gal-darah', 'Taxi Driver Axel', 'Hiromu Shimbo', 'Genevieve', 'Marcello', 'Gregg', 'Orc Female', 'FF5 Rocket Gun', 'Machamp', 'Edea'),
(2812764, 1, 'Bayleef', 'Mekgineer Thermaplugg', 'Pantheon Bomber', 'Air Force', 'Martian Manhunter', 'FF5 Mottletrap', 'King Onyx', 'Akira', 'Zeal', 'AC Rude', 'Abra', 'FF5 King Walse', 'There Was A Hole Here', 'Ramza Ruglia Mercenary', 'Rei Ayanami'),
(2812764, 2, 'Blade', 'Cleffa', 'Combo', 'Hitsugaya Toushiro', 'Fire Salamander', 'FF5 Apanda', 'Inferno Lord', 'Mammoth Graveyard', 'Lucca', 'Wiegraf Folles', 'KOS-MOS', 'Biggs', 'Warp Star', 'Dita', 'Dr Manhattan'),
(2815583, 1, '', '', '', '', '', '', '', '', '', '', 'Hexas', 'Storm Dragon', 'Abadon', 'Slime Knight', 'Seeress Leknaat'),
(2815583, 2, '', '', '', '', '', '', '', '', '', '', 'Million Knives', 'Kabuto', 'Hell Hornet', 'The Sword', 'Smith Spirit'),
(2815585, 1, '', '', '', '', '', '', '', '', '', '', 'Fiona', 'Arisu Fujisaki', 'Scizor', 'Black Arms', 'Sea Dragon'),
(2815585, 2, '', '', '', '', '', '', '', '', '', '', 'Baram', 'Kunemon', 'Elfen Knight', 'Viera Sniper', 'Sinspawn Geneaux'),
(2815613, 2, 'AC JENOVA', 'Anti Form', 'atomsplitter', 'Barbarian King', 'Blood of the Innocent', 'Blue Eyes White Dragon', 'Captain America', 'Cecil Harvey', 'Cecil the Dark Knight', 'Celebi', 'Christmas Link', 'Cid Pollendina', 'Crest', 'Curly Hill', 'D-3 Digivice'),
(2815845, 2, '', '', '', '', '', '', '', '', '', 'Momiji', '', 'Doom', 'J. D. Alazlam', 'Hydra Head', 'Pantheon Hunter'),
(2815845, 1, '', '', '', '', '', '', '', '', '', '', 'Melvin', 'Dragon Zombie', 'Bladebiter', 'Leon Lionheart', 'King Kelp'),
(2815846, 1, '', '', '', '', '', '', '', '', '', '', 'Shu', 'Siegfried', 'Abizboah', 'Delita Hyral Holy Knight', 'Miklotov'),
(2815846, 2, '', '', '', '', '', '', '', '', '', '', 'E-103 Delta', 'Black Hawk', 'E10000R', 'Zero', 'Froggy'),
(2815957, 1, '', 'Sand Golem', 'Cyber Nurse Green', 'Moloch', 'C-Thun', 'Or Wormer', 'Sinspawn Gui', 'Jenova', 'Wight Knight', 'Li-Grim', 'White Dragon', 'Carnage', 'Dark Aeons', 'Sinspawn Ammes', 'FF5 Flare'),
(0, 2, '', 'Super Tiamat', 'Dragonair', 'Dog Forms', 'Android 16', 'Long Chan Chan', 'Centaur', 'Pantheon Launcher', 'The Ouzu', 'Robin', 'Russell Barnaby', 'Ricardo Hendric', 'Summer Vivi', 'Two-Face', 'Dangaard'),
(2815959, 1, '', 'Zalbag Beoulve', 'Ridley', 'Vicious', 'Princess Ovelia Atkascha', 'Ramza Beoulve Hokuten Cadet', 'Kletian Drowa', 'Velius', 'Riou', 'Badeaux', 'Shu', 'Siegfried', 'Abizboah', 'Delita Hyral Holy Knight', 'Miklotov'),
(2815964, 2, '', '', '', '', '', '', '', '', '', '', '', 'Siegfried', 'Abizboah', 'Delita Hyral Holy Knight', 'Miklotov'),
(2815964, 1, '', '', '', '', '', '', '', '', '', '', '', '', 'Golagros', 'Bard Male', 'Ruvelia'),
(2815966, 2, '', '', '', '', '', '', '', '', '', '', 'Monk Male', 'Geomancer Male', 'Golagros', 'Bard Male', 'Ruvelia'),
(2815966, 1, '', '', '', '', '', '', '', '', '', '', 'Siegfried', 'Abizboah', 'Delita Hyral Holy Knight', 'Miklotov', 'Jess'),
(2815997, 2, 'Lilly', 'Juno And Vela', 'Doned The Streetear', 'Esper Tritoch', 'Belenus Father', 'Marill', 'Sister Claire', 'Fiend Head', 'Triforce', 'Max', 'Elder', 'Mojo', 'Leon Lionheart', 'Quagmirran', 'Metallo'),
(2815998, 2, 'Boo', 'Carniflower', 'Lisa', 'Brad', 'Gastly', 'Esper Kirin', 'Lise', 'Taxi Driver Axel', 'Slippy Toad', 'Ruvelia', 'Shogun Gekomon', 'Weepinbell', 'Altima Arch Angel', 'Kotaro', 'Larvae Moth'),
(2815999, 1, '', '', '', '', '', '', '', '', '', '', 'Carbuncle', 'Zalbag Beoulve', 'Genesis Blue Dragon', 'Summon Phoenix', 'Wingull'),
(2815999, 2, '', '', '', '', '', '', '', '', '', '', 'FF5 Azulmagia', 'Tseng', 'Bone Dragon', 'Axe Beak', 'Pip'),
(2816000, 2, 'Trapinch', 'Viera Fencer', 'Slime', 'Sado Yasutora', 'Skull Knight', 'King Triton', 'Myu', 'Rafale', 'Aquaman', 'Cyber Nurse Purple', 'Zexion', 'Allemange', 'Pantheon Warrior', 'Green Dream', 'Jun'),
(2816000, 1, '', 'Bikini Joanna Dark', 'Eidelon Leviathan', 'Alexander', 'Koroku the Dog', 'Shiftry', 'Riou', 'Mole Cerberus', 'Prop Sword', 'Phil', 'Anubis', 'Igglybuff', 'Captain Li Shang', 'Valkyrie Profile Sprite', 'Taizo Hori'),
(2816001, 2, 'Million Knives', 'Sandalphon', 'Shogun Gekomon', 'Wilder the Guide', 'Ichiro Mihara', 'Lot', 'Harpies Pet Dragon', 'Divermon', 'Two-Face', 'Ventriloquist Mel', 'Dragon Emblem', 'Nincada', 'Niagara Falls', 'Fitcher', 'FF5 Wind Drake'),
(2816001, 1, '', 'Cascoon', 'Yoshimitsu', 'Kecleon', 'Cyber Animal Turtle', 'Christmas Seifer', 'Moogle Time Mage', 'Asura Basura', 'Primera', 'Harpie Lady', 'Restless Armour', 'Gordon Freeman', 'Tien', 'Dorga', 'Blue Dragon'),
(2816017, 2, '', '', '', '', '', '', '', '', '', '', 'Priest Female', 'Kevin', 'Gen Fu', 'Sableye', 'Reno'),
(2816017, 1, '', '', '', '', '', '', '', '', '', '', 'Elf Knight', 'Destiny Bond', 'King of Artolia', 'Thunder Dragon', 'Bikini Kasumi'),
(2816020, 2, '', '', '', '', '', '', '', '', '', '', 'AC Kadaj', 'Cloud of Darkness', 'Bangaa Shopkeeper', 'Komu', 'Kasumi'),
(2816020, 1, '', '', '', '', '', '', '', '', '', '', 'Piximon', 'Summon KOTR', 'Meta Ridley', 'Cleffa', 'Leah'),
(2816193, 2, '', '', '', '', '', '', '', '', '', '', 'Zombie', 'Eagle Vision', 'FF5 Triton', 'Serra', 'Kei'),
(2816193, 1, '', '', '', '', '', '', '', '', '', '', '', 'Boh', 'Rafale', 'FF5 Geomancer', 'Unicorn Knight'),
(2816196, 1, '', '', '', '', '', '', '', '', '', 'Isadora', 'Notso Macho', 'Myu', 'Lotad', 'FF5 Little Chariot', 'William Birkin'),
(2816196, 2, '', '', '', '', '', '', '', '', 'Girimehkala', 'Spinarak', 'Princess Sara', 'Lance Knight', 'Shadowcat', 'Einlanzer', 'Mud Mannequin'),
(2816197, 2, '', '', '', 'Marshal', '', '', '', '', '', '', '', 'Abra', 'Draenei Female', 'Ezel Berbier', 'Crono'),
(2816197, 1, '', '', '', '', 'EH Wild Wingman', '', '', '', '', '', '', 'Der Wille zur Macht', 'Euryales Key', 'Koromon', 'Hammer Frame'),
(2816315, 1, '', 'Refia', 'Magnemite', 'Cyber X', 'Gorgon Urn', 'Mime Male', 'Lani', 'Kimberly', 'Kuwagust Anchus', 'Kyogre', 'Jingle', 'King Onyx', 'Yellow Opera', 'Lor-themar Theron', 'Pumpkin Bomb'),
(2816315, 2, 'Li Meiling', 'Sad Kid Asaka', 'Odette', 'Illumise', 'Freed', 'Brom', 'Rhett the 2nd Guide', 'Aku-mai', 'Gi Nattak', 'FF5 Thief', 'Pelleas', 'Lyn', 'Cornelius', 'Captain America', 'Oracle Male'),
(2816317, 2, 'Hatoko Kobayashi', 'The Basilisk', 'Calliope', 'Sasuke', 'Poo', 'Growlithe', 'Gilbert', 'Geezard', 'Mandragora', 'Arcanine', 'Blobra', 'Bukamon', 'The Flower', 'Belthasar', 'Scorpion'),
(2816317, 1, '', 'Valaha', 'Eileen', 'Gaff Gafgarion', 'Azumaril', 'Baron Jefferson', 'Albedo', 'The Wave', 'Guardian', 'Sam Fisher', 'HUcaseal', 'Siegfried Schtauffen', 'Pandemona', 'Roselia', 'Vergil'),
(2816319, 2, '', '', '', 'Grand Duke Gelkanis Barinten', '', '', '', '', '', '', '', 'Ragnarok Core', 'Ikkakumon', 'Green Hill Zone', 'Craven Cecile'),
(2816319, 1, '', '', '', '', '', '', 'Ant Lion', '', '', '', '', '', 'FF5 Mr. Clio', 'Heckran Bone', 'Celebi'),
(2816320, 1, '', '', '', '', '', '', 'Adramelk', 'Panter Flauclaws', 'Hulk', 'Ring Wyrm', 'Kakeru', 'Monster Banker', 'Stealth Tlan', 'Splasher', 'Christopher'),
(2816320, 2, '', '', '', '', '', '', 'Lezards Cat', 'Pantheon Zombie', 'Tonberry Seeker', 'Wonder Woman', 'Machinedramon', 'Buffalogre', 'Rebel Valeria', 'Freya', 'Grey'),
(2816321, 1, '', '', '', '', '', '', '', '', '', '', 'Sad Kid Asaka', 'Gyakutenno Megami', 'Yasuhiro Ueda', 'Alraune', 'The Shot'),
(2816321, 2, '', '', '', '', '', '', '', '', '', '', 'Stroke Ramuh', 'Pumpking the King of Ghosts', 'Eternal Kiss', 'Neji', 'Myrrh'),
(2816324, 1, '', 'Steamed Crab', 'Yoshi', 'Thextera', 'Madness Loki', 'The Demon Protagonist', 'Steamed Crab', 'Timon', 'Terminator', 'Yamagata', 'Happy Bunny', 'Midori', 'Gassy Marlboro', 'Boh', 'Akira'),
(2816324, 2, 'Sothe', 'Jum', 'Jigen', 'Shedinja', 'There Was A Hole Here', 'Punimon', 'FF5 Liquid Flame 2', 'Mech Soldier', 'Gnome Female', 'Great Malboro', 'Blissey', 'Polom', 'Soren', 'Strategist Albert', 'Cactoid'),
(2816325, 1, 'Bangaa Gladiator', 'Envy', 'Dwarf Female', 'Babydmon', 'Sinner Alanis', 'Giant Soldier of Stone', 'FF5 Kuzer', 'Gorgon Urn', 'Underworld Gorgon', 'Banjo-Kazooie', 'Sanyun', 'Dry Bones', 'St. Ajora Glabados', 'Persona Raphael', 'Angry Scapula'),
(2816325, 2, 'Archer Dwarf', 'Zarela, the Death Seraph', 'Kirlia', 'Fahn', 'Dark Magician Girl', 'Ninetales', 'Montimon', 'Vincent De Boule', 'Eikei', 'Fiegmund', 'True Earth Rune', 'Rouge', 'Alpha-152', 'Skorge', 'Summoner Male'),
(2816326, 1, '', '', '', '', '', '', '', '', '', '', 'Carmilla Queen', 'Barbarian King', 'Human Male', 'Stroke Ramuh', 'Nu-Mou Sage'),
(2816326, 2, '', '', '', '', '', '', '', '', '', '', 'Vexen', 'D-3 Digivice', 'Benjamin Carmine', 'Edward Elric', 'King Of Valentine'),
(2816328, 1, 'Mose', 'Chaos 0', 'EH Bubbleman', 'Corsola', 'Suiko Dwarf Chief', 'King Ymiron', 'Miklotov', 'Iron Ogre', 'Persona Cuchulainn', 'Erk', 'Eternal Memory', 'Cerveau', 'Marowak', 'Gorgon', 'Deathscythe'),
(2816329, 1, 'Village Oracle', 'Whiscash', 'Pantheon Aqua', 'Sandslash', 'Tsunomon', 'XtremelyWyld', 'Sneasel', 'Feymarch Odin', 'Prism Dress', 'Inferno', 'Novice Hix', 'Kantus', 'Booma', 'FF5 Galuf Halm Baldeson', 'BOW Nemesis'),
(2816332, 2, 'Rune God Rayearth', 'Cacturne', 'Esper Kirin', 'Sea Snake', 'Feymarch Mist Dragon', 'Clotho', 'King Boo', 'White Pikmin', 'Moogle Time Mage', 'Steamed Crab', 'Alex', 'Tarzan', 'Baigan', 'Prison Guard', 'Janice'),
(2816332, 1, 'Ghost Ship', 'Dry Bowser', 'Purple Mandoragora', 'Christmas Chrono', 'Hellbat Schilt', 'Mediator Male', 'Black Flan', 'Tentacruel', 'Deep Dive', 'Luna Bandit', 'Aila the Strange', 'Slime', 'Cyanigosa', 'FF5 Omega', 'Golem Type I'),
(2816346, 1, '', '', '', '', '', '', '', '', '', '', 'Chao', 'Xiuying', 'N Tropy', 'Varkas', 'FF5 Gilgamesh Rage'),
(2816346, 2, '', '', '', '', '', '', '', '', '', '', 'Shadow Knight', 'Kon', 'Sharpclaw', 'Magus', 'Spike Spiegel'),
(2816350, 2, '', '', '', '', '', '', '', '', '', '', 'The Shield', 'Jack Frost', 'Shade Of Eranikus', 'Dragon Mirror', 'Hydra Head'),
(2816350, 1, '', '', '', '', '', '', '', '', 'Margie', '', '', 'Dodrio', 'Pantheon Hammer', 'Jessie', 'Kangaskhan'),
(2816351, 2, '', '', '', 'Opposite Armour', '', '', '', 'Flying Demon', 'Minifrog', 'Ascot', 'Invisible Swordsman', 'Kashell', 'Fiddle Player Toppo', 'Surfing Pikachu', 'Miihen Fang'),
(2816351, 1, '', 'Lich King', '', '', '', '', '', 'Mary Jane Watson', 'Diabolos', 'FF5 Page 128', 'Penthesilia', 'Destiny Calls', 'Emeralda', 'Old Man', 'Giga Bowser'),
(2816352, 1, '', 'Rhydon', 'Craft', 'Dante', 'Mickey and Minnie', 'Harpy', 'Toad Bond', 'Toran Castle', 'Calm Ace', 'Esper Carbunkle', 'Sealed Demon Wall', 'Water Thug', 'Celebi', 'Duke the Eagle', 'Cactoid'),
(2816353, 2, '', '', '', '', '', '', '', '', '', '', 'Tracey', 'Vileplume', 'Marge', 'Human Female', 'Persona Cerberus'),
(2816353, 1, '', '', '', '', '', '', '', '', '', '', 'Kuwagamon', 'Tom Nook', 'Dancing Devil', 'Tentacruel', 'Kiros'),
(2816354, 1, '', '', '', '', '', '', '', '', '', '', '', 'Overlord Wyrmthalak', 'Ninja', 'Shadow', 'Window'),
(2816354, 2, '', '', '', '', '', '', '', '', '', '', 'Fran', 'Fiery Pegasus', 'Deadly Hedgehog Pie', 'Canas', 'Loki'),
(2816357, 2, '', '', '', '', '', '', '', '', '', '', 'Bizarro Sephiroth', 'Horny Elaine', 'Water Flan', 'FF5 Atomos', 'Babus Swain'),
(2816357, 1, '', '', '', '', '', '', '', '', '', '', 'Eden', 'L Devout', 'Pupitar', 'Christmas Megaman', 'Volvagia'),
(2816358, 1, '', '', '', '', '', '', '', '', '', '', 'Leonardo', 'Materia Keeper', 'Bugbear', 'Aries', 'Zu'),
(2816358, 2, '', '', '', '', '', '', '', '', '', '', 'Alcyone', 'Kefka', 'Chi-You', 'Minoru Kokubunji', 'Urstrix'),
(2816359, 2, '', '', '', '', '', '', '', '', '', '', 'Geezard', 'Time Egg', 'Miluda Folles', 'Porygon2', 'Mythril Cait Sith'),
(2816359, 1, '', '', '', '', '', '', '', '', '', '', 'Sakura', 'Griffin', 'Pinsir', 'Black Hawk', 'Old Man'),
(2816373, 1, '', '', '', '', '', '', '', '', '', '', '', 'Chocobo Farm', 'Curley', 'Kotaro Kobayashi', 'Leanan Sidhe'),
(2816373, 2, '', '', '', '', '', '', '', '', '', '', 'FF5 Skeleton', 'Tentomon', 'Odette', 'Young Belenus', 'Chrono'),
(2816374, 1, '', '', 'Decor Shield', 'Squidraken', 'Krelian', 'Gui Zhang', 'Vazruden The Herald', 'Frieza', 'Vegeta', 'Captain Legionnaire', 'Namine', 'Rinoa', 'Hitomi', 'Young Selphie', 'Hinata'),
(2816374, 2, '', 'Zagato', 'Mino Magnus', 'Pupitar', 'Defender X', 'Cairne Bloodhoof', 'Horn', 'Sick Animal Franz', 'Serenitys Children', 'Hai Lan Scout', 'Red Pikmin', 'Estella the Lewd', 'Tony', 'AC Zack', 'Dante The Demon Slayer'),
(2816375, 1, '', '', '', '', '', '', '', '', '', '', '', 'Dragon Emblem', 'FLUDD', 'Wario', 'Urstrix'),
(2816375, 2, '', '', '', '', '', '', '', '', '', '', 'Mana Stone', 'Marcy', 'Demoman', 'Kazuya', 'King Behemoth'),
(2816387, 2, '', '', '', '', '', '', '', '', '', '', 'Jecht Shot', 'AC Zack', 'Parasite Cage', 'Piranha', 'Red Samurai'),
(2816387, 1, '', '', '', '', '', '', '', '', '', '', '', 'Zero', 'The Float', 'Tir Mcdohl', 'Summon Odin'),
(2816389, 2, '', '', '', '', '', '', '', '', '', '', '', 'Ose', 'Luna', 'Kecleon', 'Kala'),
(2816389, 1, '', '', '', '', '', '', '', '', '', '', '', 'Zenigata', 'FF5 King Behemoth', 'God of War', 'Pandoras Chest'),
(2816400, 1, '', '', '', 'Wizard Female', '', '', '', '', '', '', 'Tony', 'FF5 Ifrit', 'Spectral Keeper', 'True Runes', 'Monopoly Man'),
(2816400, 2, '', 'Princess Hilda', '', '', '', '', '', '', '', '', 'Liquid Metal Slime', 'Paul', 'Gloom', 'Smith Spirit', 'Frei'),
(2816401, 1, '', '', 'Mischievous Mole', '', '', '', '', '', '', '', 'Kuro', 'Olette', 'EH Neos Alius', 'Boss Black Dragon', 'Irenes'),
(2816401, 2, '', '', 'Agares', '', '', '', '', '', '', '', 'Brittle Tuta', 'Gligar', 'Neofio', 'Shiho', 'Human Warrior'),
(2816421, 1, '', 'Copy X', '', '', '', '', '', '', '', '', '', 'Himawari', 'Ditto', 'Yabby', 'FF5 Brand Lamia'),
(2816421, 2, '', 'Super Mushroom', '', '', '', '', '', '', '', '', '', 'Alexander', 'Crash Bandicoot', 'Battle Queen', 'Toad Bond'),
(2816427, 1, '', '', '', '', '', '', '', 'Archer Female', '', '', '', 'Stantler', 'Gizamon', 'Coin', 'Blue Dragon'),
(2816427, 2, '', '', '', '', '', '', '', '', '', 'Rogue Tomato', 'Margie', 'Freedom', 'Minakata', 'Democrobot', 'Jawbreaker'),
(2816448, 1, '', 'Rei Ayanami', 'Zalbag Beoulve Undead', 'Power Girl', 'Master Ninja', 'Armoured Knight', 'Petey Piranha', 'Celebi', 'Cheese', 'Chang Ang', 'Thames', 'Alraune', 'Beiji Weng', 'Christmas Vivi', 'Grobyc'),
(2816549, 2, '', '', '', '', '', '', '', '', '', 'Great Troll', 'Invisible Swordsman', 'Stone Golem', 'Anchorman', 'Bard Male', 'Besrodio Bunanza'),
(2816549, 1, '', '', '', '', '', '', '', '', '', 'Kou Shishido', 'Jowy Atreides', 'Bowser', 'Link', 'Kairi', 'Mario'),
(2816310, 1, '', '', '', '', '', '', '', '', '', '', '', 'The Punisher', 'Eye of Rimsala', 'Birdramon', 'Purple Valkyrie Warrior'),
(2816310, 2, '', '', '', '', '', '', '', '', '', '', '', 'Warp Star', 'Toran Castle', 'Astaroth', 'Pyro Jack'),
(2816482, 1, '', '', '', '', '', '', '', '', '', '', 'Sakura Kasugano', 'EH Dark Neos', 'Gil Snapper', 'Summer Cloud', 'FF5 Apanda'),
(2816482, 2, '', '', '', '', '', '', '', '', '', '', 'Big Malboro', 'Dark Emperor Jet Black', 'Bikini Joanna Dark', 'Catoblepas', 'Pantheon Zombie'),
(2816563, 2, '', '', '', '', '', '', '', '', '', '', '', 'Marche Radiuju', 'Mitsuru Kijiro', 'Knight Female', 'Ice Titan'),
(2816563, 1, '', '', '', '', '', '', '', '', '', '', '', '', 'Team Aqua', 'Irenes', 'Assistant Elisabeth'),
(2816706, 1, '', '', '', '', '', '', '', '', '', '', 'Magikarp', 'Devi Devimon', '(DW1) Specter', 'Volcanic Rocket', 'Mafdet'),
(2816706, 2, '', '', '', '', '', '', '', '', '', '', 'Snipe Hunter', 'Snow Lion', 'FF5 Tunneller', 'Archer Female', 'Ayane'),
(2816834, 1, '', '', '', '', '', '', '', '', '', '', 'Young Joshua', 'Boco', 'Ezel Berbier', 'Emperor Mateus', 'Christmas Seifer'),
(2816834, 2, '', '', '', '', '', '', '', '', '', '', 'Lezards Cat', 'Killer Snail', 'Hikaru Shidou', 'Norris', 'Esper ZoneSeek'),
(2816835, 2, 'The Human Protagonist', 'Vargas', 'Spearook', 'Isabella', 'FF5 Fan Wizard', 'Hammerhead', 'Don Zaloog', 'Feymarch Asura', 'FF5 Dragon Grass', 'Haruka Urashima', '(DW2) Evil Clown', 'Grimguard', 'Mr Freeze', 'The Commander', 'Swingin Hipster'),
(2816835, 1, '', '(DW2) Saber Tiger', 'Esper Palidor', 'Summon Bahumat', 'FF5 La Mage', 'FF5 Bard', 'Minayo', 'Fitcher', 'Lileep', 'Benjamin Carmine', 'Jelly', 'Koopa Troopa', 'Mal Ganis', 'Steamed Crab', 'EH Rampart Bluster'),
(2816959, 2, '', '', 'Pokeball', 'Desert Sahagin', 'Red Skull', 'Gengar', 'Numemon', 'Hugo', 'Chrono Cross', 'Dark Opera', 'Judge Ghis', 'KOS-MOS', 'Kratos', 'Bigeau', 'Bouncy Wild'),
(2816959, 1, '', '', '(DW1) Magician', 'Stealth Sneak', 'Warlord Kalithresh', 'Luccia', 'Summer Hugo', 'Cyber Hacker Ninja', 'Pidgeotto', 'Tsai', 'PokeBlocks', 'Judge Man', 'Gengar', 'Leeknat', 'Beast'),
(2816960, 1, '', '', '', '', '', '', '', '', '', '', 'Centaur Knight', 'Beautifly', 'R Red Mage', 'Lezards Cat', 'FF5 Blue Dragon'),
(2816960, 2, '', '', '', '', '', '', '', '', '', '', 'Den Antlion', 'Geo Metro', 'Blazing Chimera', '(DW2) Metal Slime', 'Bigeau'),
(2817016, 2, 'The Little', 'Incubus', 'AC Rude', 'Persona Titan', 'Jonny', 'Behemoth', 'Carlito', 'Aeon Mindy', 'Thrustaevis', 'Buu', 'Bomb', 'Thor', 'Demon Wall', 'Cardinal Alphons Draclau', 'Tempete'),
(2817016, 1, 'Cassie', 'Joshua Levenheit', 'Doctor Cid', 'Wisdom Form', 'Luc', 'Leilas Boat', 'Piscodaemon', 'Yam Koo', 'Star Dragon Sword', 'Splasher', 'Aeon Ixion', 'Zexion', 'Rafale', 'Gerald Robotnik', 'Kinnison'),
(2817017, 2, 'Shiva', 'Koromaru', 'Devi Devimon', 'Joshua Levenheit', 'Boo', 'Bigeau', 'Cunning Hortez VII', 'Gremlin Mage', 'Christmas Kirby', 'Vampire Night', 'Kyuubi', 'Kala', 'Kun to', 'The Atom', 'Shadow'),
(2817017, 1, 'Yoruichi Shihouin', 'Walrein', 'Black Mushroom', 'Stallion', 'Erk', 'Kanaan', 'Cecil Harvey', 'Tri-Face', 'Ochu', 'Goddess', 'The Shadow', 'Doom Gaze', 'Pumpkin Bomb', 'Simba', 'Anji');
