Public Class Encryption
    Public Function Decode(ByVal sText As String) As String

        Dim x As Integer
        Dim sDecode As String

        For x = 1 To Len(sText) Step 2
            sDecode = sDecode & DecodeMap(Mid(sText, x, 2))
        Next x

        Decode = sDecode
    End Function

    Public Function Encode(ByVal sText As String) As String

        Dim x As Integer
        Dim sEncode As String

        For x = 1 To Len(sText)
            sEncode = sEncode & EncodeMap(Mid(sText, x, 1))
        Next x

        Encode = sEncode
    End Function

    Private Function EncodeMap(ByVal sChar As String) As String

        Dim sEncode As String

        Select Case sChar
            Case "a"
                sEncode = "A1"
            Case "b"
                sEncode = "A2"
            Case "c"
                sEncode = "A3"
            Case "d"
                sEncode = "A4"
            Case "e"
                sEncode = "A5"
            Case "f"
                sEncode = "A6"
            Case "g"
                sEncode = "A7"
            Case "h"
                sEncode = "A8"
            Case "i"
                sEncode = "A9"
            Case "j"
                sEncode = "B0"
            Case "k"
                sEncode = "B1"
            Case "l"
                sEncode = "B2"
            Case "m"
                sEncode = "B3"
            Case "n"
                sEncode = "B4"
            Case "o"
                sEncode = "B5"
            Case "p"
                sEncode = "B6"
            Case "q"
                sEncode = "B7"
            Case "r"
                sEncode = "B8"
            Case "s"
                sEncode = "B9"
            Case "t"
                sEncode = "C0"
            Case "u"
                sEncode = "C1"
            Case "v"
                sEncode = "C2"
            Case "w"
                sEncode = "C3"
            Case "y"
                sEncode = "C4"
            Case "z"
                sEncode = "C5"
            Case "A"
                sEncode = "C6"
            Case "B"
                sEncode = "C7"
            Case "C"
                sEncode = "C8"
            Case "D"
                sEncode = "C9"
            Case "E"
                sEncode = "D0"
            Case "F"
                sEncode = "D1"
            Case "G"
                sEncode = "D2"
            Case "H"
                sEncode = "D3"
            Case "I"
                sEncode = "D4"
            Case "J"
                sEncode = "D5"
            Case "K"
                sEncode = "D6"
            Case "L"
                sEncode = "D7"
            Case "M"
                sEncode = "D8"
            Case "N"
                sEncode = "D9"
            Case "O"
                sEncode = "E0"
            Case "P"
                sEncode = "E1"
            Case "Q"
                sEncode = "E2"
            Case "R"
                sEncode = "E3"
            Case "S"
                sEncode = "E4"
            Case "T"
                sEncode = "E5"
            Case "U"
                sEncode = "E6"
            Case "V"
                sEncode = "E7"
            Case "W"
                sEncode = "E8"
            Case "X"
                sEncode = "E9"
            Case "Y"
                sEncode = "F0"
            Case "Z"
                sEncode = "F1"
            Case "0"
                sEncode = "F2"
            Case "1"
                sEncode = "F3"
            Case "2"
                sEncode = "F4"
            Case "3"
                sEncode = "F5"
            Case "4"
                sEncode = "F6"
            Case "5"
                sEncode = "F7"
            Case "6"
                sEncode = "F8"
            Case "7"
                sEncode = "F9"
            Case "8"
                sEncode = "G0"
            Case "9"
                sEncode = "G1"
            Case "%20"
                sEncode = "Z9"
            Case "!"
                sEncode = "G2"
            Case "@"
                sEncode = "G3"
            Case "#"
                sEncode = "G4"
            Case "$"
                sEncode = "G5"
            Case "%"
                sEncode = "G6"
            Case "^"
                sEncode = "G7"
            Case "&"
                sEncode = "G8"
            Case "*"
                sEncode = "G9"
            Case "("
                sEncode = "H0"
            Case ")"
                sEncode = "H1"
            Case "-"
                sEncode = "H2"
            Case "_"
                sEncode = "H3"
            Case "+"
                sEncode = "H4"
            Case "="
                sEncode = "H5"
            Case "<"
                sEncode = "H6"
            Case ">"
                sEncode = "H7"
            Case ","
                sEncode = "H8"
            Case "."
                sEncode = "H9"
            Case "?"
                sEncode = "I0"
            Case "/"
                sEncode = "I1"
            Case ";"
                sEncode = "I2"
            Case ":"
                sEncode = "I3"
            Case "'"
                sEncode = "I4"
            Case "["
                sEncode = "I5"
            Case "]"
                sEncode = "I6"
            Case "{"
                sEncode = "I7"
            Case "}"
                sEncode = "I8"
            Case "|"
                sEncode = "I9"
            Case "\"
                sEncode = "J0"
            Case "`"
                sEncode = "J1"
            Case "~"
                sEncode = "J2"
            Case " "
                sEncode = "J3"
        End Select

        EncodeMap = sEncode
    End Function

    Private Function DecodeMap(ByVal sChar As String) As String

        Dim sDecode As String

        Select Case sChar
            Case "A1"
                sDecode = "a"
            Case "A2"
                sDecode = "b"
            Case "A3"
                sDecode = "c"
            Case "A4"
                sDecode = "d"
            Case "A5"
                sDecode = "e"
            Case "A6"
                sDecode = "f"
            Case "A7"
                sDecode = "g"
            Case "A8"
                sDecode = "h"
            Case "A9"
                sDecode = "i"
            Case "B0"
                sDecode = "j"
            Case "B1"
                sDecode = "k"
            Case "B2"
                sDecode = "l"
            Case "B3"
                sDecode = "m"
            Case "B4"
                sDecode = "n"
            Case "B5"
                sDecode = "o"
            Case "B6"
                sDecode = "p"
            Case "B7"
                sDecode = "q"
            Case "B8"
                sDecode = "r"
            Case "B9"
                sDecode = "s"
            Case "C0"
                sDecode = "t"
            Case "C1"
                sDecode = "u"
            Case "C2"
                sDecode = "v"
            Case "C3"
                sDecode = "w"
            Case "C4"
                sDecode = "y"
            Case "C5"
                sDecode = "z"
            Case "C6"
                sDecode = "A"
            Case "C7"
                sDecode = "B"
            Case "C8"
                sDecode = "C"
            Case "C9"
                sDecode = "D"
            Case "D0"
                sDecode = "E"
            Case "D1"
                sDecode = "F"
            Case "D2"
                sDecode = "G"
            Case "D3"
                sDecode = "H"
            Case "D4"
                sDecode = "I"
            Case "D5"
                sDecode = "J"
            Case "D6"
                sDecode = "K"
            Case "D7"
                sDecode = "L"
            Case "D8"
                sDecode = "M"
            Case "D9"
                sDecode = "N"
            Case "E0"
                sDecode = "O"
            Case "E1"
                sDecode = "P"
            Case "E2"
                sDecode = "Q"
            Case "E3"
                sDecode = "R"
            Case "E4"
                sDecode = "S"
            Case "E5"
                sDecode = "T"
            Case "E6"
                sDecode = "U"
            Case "E7"
                sDecode = "V"
            Case "E8"
                sDecode = "W"
            Case "E9"
                sDecode = "X"
            Case "F0"
                sDecode = "Y"
            Case "F1"
                sDecode = "Z"
            Case "F2"
                sDecode = "0"
            Case "F3"
                sDecode = "1"
            Case "F4"
                sDecode = "2"
            Case "F5"
                sDecode = "3"
            Case "F6"
                sDecode = "4"
            Case "F7"
                sDecode = "5"
            Case "F8"
                sDecode = "6"
            Case "F9"
                sDecode = "7"
            Case "G0"
                sDecode = "8"
            Case "G1"
                sDecode = "9"
            Case "Z9"
                sDecode = "%20"
            Case "G2"
                sDecode = "!"
            Case "G3"
                sDecode = "@"
            Case "G4"
                sDecode = "#"
            Case "G5"
                sDecode = "$"
            Case "G6"
                sDecode = "%"
            Case "G7"
                sDecode = "^"
            Case "G8"
                sDecode = "&"
            Case "G9"
                sDecode = "*"
            Case "H0"
                sDecode = "("
            Case "H1"
                sDecode = ")"
            Case "H2"
                sDecode = "-"
            Case "H3"
                sDecode = "_"
            Case "H4"
                sDecode = "+"
            Case "H5"
                sDecode = "="
            Case "H6"
                sDecode = "<"
            Case "H7"
                sDecode = ">"
            Case "H8"
                sDecode = ","
            Case "H9"
                sDecode = "."
            Case "I0"
                sDecode = "?"
            Case "I1"
                sDecode = "/"
            Case "I2"
                sDecode = ";"
            Case "I3"
                sDecode = ":"
            Case "I4"
                sDecode = "'"
            Case "I5"
                sDecode = "["
            Case "I6"
                sDecode = "]"
            Case "I7"
                sDecode = "{"
            Case "I8"
                sDecode = "}"
            Case "I9"
                sDecode = "|"
            Case "J0"
                sDecode = "\"
            Case "J1"
                sDecode = "`"
            Case "J2"
                sDecode = "~"
            Case "J3"
                sDecode = " "
        End Select

        DecodeMap = sDecode

    End Function
End Class